//! Byte-parity replay of the TE06 golden fixtures
//! (`fixtures/generated/smart-fetch-parity/`, generated by
//! `scripts/smart-fetch-parity/gen-fixtures.mjs` against the PINNED upstream
//! agent-smart-fetch v0.3.17 / b0111612).
//!
//! Every case records the upstream output for a fixed input; the port must
//! reproduce it exactly. Pipeline scenarios replay through the injected
//! transport + extractor seams — the same mock strategy the upstream unit
//! tests use (`createDefuddleFetch` with `FetchDependencies`), so both sides
//! see identical scripted responses, thrown errors and extraction results.

use std::collections::BTreeMap;
use std::str::FromStr as _;
use std::sync::{Arc, Mutex};

use rpi_ext_smart_fetch::batch::{self, BatchFetchItemResult, BatchFetchResult};
use rpi_ext_smart_fetch::extract::{ExtractOptions, Extractor};
use rpi_ext_smart_fetch::format;
use rpi_ext_smart_fetch::http::{FetchFailure, HttpRequest, HttpResponse};
use rpi_ext_smart_fetch::pipeline::{futures_boxed, FetchPipeline, TransportFn};
use rpi_ext_smart_fetch::settings;
use rpi_ext_smart_fetch::types::FetchToolConfig;
use rpi_ext_smart_fetch::types::{
    ExtractedContent, FetchError, FetchOptions, FetchOutcome, FetchResult, IncludeReplies,
    OutputFormat,
};
use serde_json::{json, Value};

const FIXTURES: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/generated/smart-fetch-parity"
);

fn load(name: &str) -> Value {
    let path = format!("{FIXTURES}/{name}");
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("read {path}: {error} — run gen-fixtures.mjs first"));
    serde_json::from_str(&raw).expect("fixture JSON parses")
}

fn cases(document: &Value, group: &str) -> Vec<Value> {
    document
        .get(group)
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default()
}

fn str_field(value: &Value, key: &str) -> String {
    value
        .get(key)
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_string()
}

// ---------------------------------------------------------------------------
// A. format.json
// ---------------------------------------------------------------------------

#[test]
fn parity_markdown_to_text() {
    for case in cases(&load("format.json"), "markdownToText") {
        let input = str_field(&case, "input");
        let expected = str_field(&case, "output");
        assert_eq!(
            format::markdown_to_text(&input),
            expected,
            "case {}",
            str_field(&case, "name")
        );
    }
}

#[test]
fn parity_truncate_content() {
    let mut diffs = Vec::new();
    for case in cases(&load("format.json"), "truncateContent") {
        let input = case.get("input").expect("input");
        let content = input
            .get("content")
            .and_then(Value::as_str)
            .unwrap_or_default();
        let max_chars = input
            .get("maxChars")
            .and_then(Value::as_u64)
            .unwrap_or_default();
        let actual = format::truncate_content(content, max_chars);
        let expected = str_field(&case, "output");
        if actual != expected {
            // [VARIANT] FR-P0-9: UTF-16 vs char-boundary truncation drift on
            // astral inputs — record, don't fail (the two astral cases are
            // the declared drift samples).
            diffs.push(format!(
                "{}: expected {:?} got {:?}",
                str_field(&case, "name"),
                expected,
                actual
            ));
        }
    }
    let non_variant: Vec<_> = diffs.iter().filter(|d| !d.starts_with("astral")).collect();
    assert!(
        non_variant.is_empty(),
        "non-astral truncation drifted: {non_variant:?}"
    );
    println!("truncateContent astral [VARIANT] drift samples: {diffs:?}");
}

#[test]
fn parity_estimate_word_count() {
    for case in cases(&load("format.json"), "estimateWordCount") {
        let input = str_field(&case, "input");
        let expected = case
            .get("output")
            .and_then(Value::as_u64)
            .unwrap_or_default();
        assert_eq!(
            format::estimate_word_count(&input),
            expected,
            "case {}",
            str_field(&case, "name")
        );
    }
}

#[test]
fn parity_escape_html() {
    for case in cases(&load("format.json"), "escapeHtml") {
        let input = str_field(&case, "input");
        let expected = str_field(&case, "output");
        assert_eq!(
            format::escape_html(&input),
            expected,
            "case {}",
            str_field(&case, "name")
        );
    }
}

#[test]
fn parity_parse_and_format_json() {
    for case in cases(&load("format.json"), "parseAndFormatJson") {
        let input = str_field(&case, "input");
        let output = case.get("output").expect("output");
        match format::parse_and_format_json(&input) {
            Ok(formatted) => assert_eq!(
                formatted,
                str_field(output, "formatted"),
                "case {}",
                str_field(&case, "name")
            ),
            Err(message) => assert_eq!(
                message,
                str_field(output, "error"),
                "case {}",
                str_field(&case, "name")
            ),
        }
    }
}

#[test]
fn parity_render_json_content() {
    for case in cases(&load("format.json"), "renderJsonContent") {
        let input = case.get("input").expect("input");
        let formatted = str_field(input, "formatted");
        let format_name = str_field(input, "format");
        let format = OutputFormat::from_str(format_name.as_str()).expect("format");
        assert_eq!(
            format::render_json_content(&formatted, format),
            str_field(&case, "output"),
            "case {}",
            str_field(&case, "name")
        );
    }
}

#[test]
fn parity_strip_extractor_comments() {
    for case in cases(&load("format.json"), "stripExtractorComments") {
        let input = case.get("input").expect("input");
        let content = str_field(input, "content");
        let format = OutputFormat::from_str(str_field(input, "format").as_str()).expect("format");
        assert_eq!(
            format::strip_extractor_comments(&content, format),
            str_field(&case, "output"),
            "case {}",
            str_field(&case, "name")
        );
    }
}

#[test]
fn parity_metadata_headers_and_response_texts() {
    let document = load("format.json");
    for case in cases(&document, "metadataHeaders") {
        let input = case.get("input").expect("input");
        let result: FetchResult =
            serde_json::from_value(input.get("result").cloned().expect("result"))
                .expect("FetchResult replays");
        let verbose = input
            .get("verbose")
            .and_then(Value::as_bool)
            .unwrap_or(false);
        let actual = if verbose {
            format::build_metadata_header(&result)
        } else {
            format::build_compact_metadata_header(&result)
        };
        assert_eq!(
            actual,
            str_field(&case, "output"),
            "case {}",
            str_field(&case, "name")
        );
    }
    for case in cases(&document, "responseTexts") {
        let input = case.get("input").expect("input");
        let result: FetchResult =
            serde_json::from_value(input.get("result").cloned().expect("result"))
                .expect("FetchResult replays");
        let verbose = input
            .get("verbose")
            .and_then(Value::as_bool)
            .unwrap_or(false);
        assert_eq!(
            format::build_fetch_response_text(&result, verbose),
            str_field(&case, "output"),
            "case {}",
            str_field(&case, "name")
        );
    }
}

#[test]
fn parity_error_response_texts_and_summaries() {
    let document = load("format.json");
    for case in cases(&document, "errorResponseTexts") {
        let error: FetchError = serde_json::from_value(case.get("input").cloned().expect("input"))
            .expect("FetchError replays");
        assert_eq!(
            format::build_fetch_error_response_text(&error),
            str_field(&case, "output"),
            "case {}",
            str_field(&case, "name")
        );
    }
    for case in cases(&document, "errorSummaries") {
        let error: FetchError = serde_json::from_value(case.get("input").cloned().expect("input"))
            .expect("FetchError replays");
        assert_eq!(
            format::build_user_facing_fetch_error_summary(&error),
            str_field(&case, "output"),
            "case {}",
            str_field(&case, "name")
        );
    }
}

#[test]
fn parity_batch_response_text() {
    for case in cases(&load("format.json"), "batchResponseText") {
        let input = case.get("input").expect("input");
        let upstream = input.get("result").expect("result");
        let mut items = Vec::new();
        for item in upstream
            .get("items")
            .and_then(Value::as_array)
            .unwrap_or(&Vec::new())
        {
            items.push(BatchFetchItemResult {
                index: item
                    .get("index")
                    .and_then(Value::as_u64)
                    .unwrap_or_default() as usize,
                request_url: item
                    .get("request")
                    .and_then(|r| r.get("url"))
                    .and_then(Value::as_str)
                    .unwrap_or_default()
                    .to_string(),
                status: if item.get("status").and_then(Value::as_str) == Some("error") {
                    "error"
                } else {
                    "done"
                },
                error: item
                    .get("error")
                    .and_then(Value::as_str)
                    .map(str::to_string),
                result: item.get("result").map(|result| {
                    serde_json::from_value(result.clone()).expect("FetchResult replays")
                }),
            });
        }
        let batch = BatchFetchResult {
            items,
            total: upstream
                .get("total")
                .and_then(Value::as_u64)
                .unwrap_or_default(),
            succeeded: upstream
                .get("succeeded")
                .and_then(Value::as_u64)
                .unwrap_or_default(),
            failed: upstream
                .get("failed")
                .and_then(Value::as_u64)
                .unwrap_or_default(),
            batch_concurrency: upstream
                .get("batchConcurrency")
                .and_then(Value::as_u64)
                .unwrap_or_default(),
        };
        let verbose = input
            .get("verbose")
            .and_then(Value::as_bool)
            .unwrap_or(false);
        assert_eq!(
            batch::build_batch_fetch_response_text(&batch, verbose),
            str_field(&case, "output"),
            "case {}",
            str_field(&case, "name")
        );
    }
}

// ---------------------------------------------------------------------------
// B. tool.json / C. settings.json (JSON-shape comparison)
// ---------------------------------------------------------------------------

#[test]
fn parity_resolve_fetch_tool_defaults() {
    for case in cases(&load("tool.json"), "resolveFetchToolDefaults") {
        let config: FetchToolConfig = config_from_json(case.get("input").expect("input"));
        let defaults = batch::resolve_fetch_tool_defaults(&config);
        let actual = json!({
            "maxChars": defaults.max_chars,
            "timeoutMs": defaults.timeout_ms,
            "browser": defaults.browser,
            "os": defaults.os,
            "removeImages": defaults.remove_images,
            "includeReplies": include_replies_json(&defaults.include_replies),
            "batchConcurrency": defaults.batch_concurrency,
        });
        // upstream omits unset tempDir (undefined) — mirror that by only
        // comparing keys the fixture carries
        let mut expected = case.get("output").cloned().unwrap_or(Value::Null);
        if let Some(object) = expected.as_object_mut() {
            object.remove("tempDir");
        }
        assert_eq!(
            actual,
            strip_nullish(expected),
            "case {}",
            str_field(&case, "name")
        );
    }
}

#[test]
fn parity_resolve_settings() {
    for case in cases(&load("settings.json"), "resolvePiSmartFetchSettings") {
        let input = case.get("input").expect("input");
        let global = input.get("global").cloned().unwrap_or(json!({}));
        let project = input.get("project").cloned().unwrap_or(json!({}));
        let resolved = settings::resolve_settings(&global, &project);
        let actual = json!({
            "verboseByDefault": resolved.verbose_by_default,
            "maxChars": resolved.config.max_chars,
            "timeoutMs": resolved.config.timeout_ms,
            "browser": resolved.config.browser,
            "os": resolved.config.os,
            "removeImages": resolved.config.remove_images,
            "includeReplies": resolved.config.include_replies.as_ref().map(include_replies_json),
            "batchConcurrency": resolved.config.batch_concurrency,
            "tempDir": resolved.config.temp_dir,
        });
        // The temp-dir default is the declared [VARIANT] (upstream
        // smart-fetch-pi vs rpi smart-fetch-rpi) and the path prefix is
        // host-specific — normalize both sides to the shared stem form
        // "<TMPDIR>/smart-fetch-<NAME>".
        let normalize_temp_dir = |mut value: Value| {
            if let Some(dir) = value.get("tempDir").and_then(Value::as_str) {
                if let Some((_, tail)) = dir.rsplit_once("/smart-fetch-") {
                    let _ = tail; // -pi vs -rpi is the declared variant
                    value["tempDir"] = json!("<TMPDIR>/smart-fetch-<NAME>");
                }
            }
            value
        };
        let expected = case.get("output").cloned().unwrap_or(Value::Null);
        assert_eq!(
            normalize_temp_dir(strip_nullish(actual)),
            normalize_temp_dir(strip_nullish(expected)),
            "case {}",
            str_field(&case, "name")
        );
    }
}

fn config_from_json(value: &Value) -> FetchToolConfig {
    FetchToolConfig {
        max_chars: value.get("maxChars").and_then(Value::as_u64),
        timeout_ms: value.get("timeoutMs").and_then(Value::as_u64),
        browser: value
            .get("browser")
            .and_then(Value::as_str)
            .map(str::to_string),
        os: value.get("os").and_then(Value::as_str).map(str::to_string),
        remove_images: value.get("removeImages").and_then(Value::as_bool),
        include_replies: value.get("includeReplies").map(include_replies_from_json),
        batch_concurrency: value.get("batchConcurrency").and_then(Value::as_f64),
        temp_dir: value
            .get("tempDir")
            .and_then(Value::as_str)
            .map(str::to_string),
    }
}

fn include_replies_from_json(value: &Value) -> IncludeReplies {
    match value {
        Value::Bool(true) => IncludeReplies::All,
        Value::Bool(false) => IncludeReplies::None,
        Value::String(s) if s == "extractors" => IncludeReplies::Extractors,
        _ => IncludeReplies::Extractors,
    }
}

fn include_replies_json(value: &IncludeReplies) -> Value {
    match value {
        IncludeReplies::All => json!(true),
        IncludeReplies::None => json!(false),
        IncludeReplies::Extractors => json!("extractors"),
    }
}

/// JS `JSON.stringify` drops undefined keys; None/absent must compare equal.
fn strip_nullish(value: Value) -> Value {
    match value {
        Value::Object(map) => Value::Object(
            map.into_iter()
                .filter(|(_, v)| !v.is_null())
                .map(|(k, v)| (k, strip_nullish(v)))
                .collect(),
        ),
        other => other,
    }
}

// ---------------------------------------------------------------------------
// D. pipeline.json — mocked transport + extractor replay
// ---------------------------------------------------------------------------

struct ScriptedExtractor(ExtractedContent);

impl Extractor for ScriptedExtractor {
    fn extract(&self, _html: &str, _url: &str, _options: &ExtractOptions) -> ExtractedContent {
        self.0.clone()
    }
}

fn extracted_from_json(value: &Value) -> ExtractedContent {
    ExtractedContent {
        content: value
            .get("content")
            .and_then(Value::as_str)
            .map(str::to_string),
        word_count: value.get("wordCount").and_then(Value::as_u64).unwrap_or(0),
        title: value
            .get("title")
            .and_then(Value::as_str)
            .map(str::to_string),
        author: value
            .get("author")
            .and_then(Value::as_str)
            .map(str::to_string),
        published: value
            .get("published")
            .and_then(Value::as_str)
            .map(str::to_string),
        site: value
            .get("site")
            .and_then(Value::as_str)
            .map(str::to_string),
        language: value
            .get("language")
            .and_then(Value::as_str)
            .map(str::to_string),
        extractor_type: None,
    }
}

fn options_from_json(value: &Value) -> FetchOptions {
    let headers = value.get("headers").and_then(Value::as_object).map(|map| {
        map.iter()
            .filter_map(|(name, value)| {
                value
                    .as_str()
                    .map(|value| (name.clone(), value.to_string()))
            })
            .collect::<BTreeMap<String, String>>()
    });
    FetchOptions {
        url: str_field(value, "url"),
        browser: value
            .get("browser")
            .and_then(Value::as_str)
            .map(str::to_string),
        os: value.get("os").and_then(Value::as_str).map(str::to_string),
        headers,
        format: value
            .get("format")
            .and_then(Value::as_str)
            .and_then(|name| OutputFormat::from_str(name).ok()),
        max_chars: value.get("maxChars").and_then(Value::as_u64),
        remove_images: value.get("removeImages").and_then(Value::as_bool),
        include_replies: value.get("includeReplies").map(include_replies_from_json),
        proxy: value
            .get("proxy")
            .and_then(Value::as_str)
            .map(str::to_string),
        timeout_ms: value.get("timeoutMs").and_then(Value::as_u64),
        temp_dir: value
            .get("tempDir")
            .and_then(Value::as_str)
            .map(str::to_string),
    }
}

#[tokio::test]
async fn parity_pipeline_scenarios() {
    let scenarios = load("pipeline.json");
    let scenarios = scenarios.as_array().cloned().unwrap_or_default();
    assert!(!scenarios.is_empty(), "pipeline fixtures missing");

    // Declared P0 scope exceptions (TE06 task file):
    // - maxchars-astral-variant: FR-P0-9 [VARIANT] — UTF-16 vs char-boundary
    //   truncation drift; the fixture records the upstream sample, content is
    //   compared by char-prefix only.
    // - non-html-content-type: upstream streams binaries to a temp file
    //   (FR-P1-4, TE07); the P0 pipeline terminates at "Not an HTML page".
    //   Re-assert equality once the download branch lands.
    const SKIP_RESULT: [&str; 1] = ["non-html-content-type"];
    const ASTRAL_VARIANT: [&str; 1] = ["maxchars-astral-variant"];

    let mut failures = Vec::new();
    for scenario in &scenarios {
        let name = str_field(scenario, "name");
        let input = scenario.get("input").expect("input");
        let opts = options_from_json(input.get("opts").expect("opts"));
        let scripted_extraction = ScriptedExtractor(extracted_from_json(
            input.get("defuddleResult").expect("defuddle"),
        ));
        let script: Vec<Value> = input
            .get("fetchScript")
            .and_then(Value::as_array)
            .cloned()
            .unwrap_or_default();

        let steps: Arc<Mutex<Vec<Value>>> = Arc::new(Mutex::new(script));
        let seen_headers: Arc<Mutex<Option<BTreeMap<String, String>>>> = Arc::new(Mutex::new(None));
        let seen_timeout: Arc<Mutex<Option<u64>>> = Arc::new(Mutex::new(None));
        let seen_proxy: Arc<Mutex<Option<String>>> = Arc::new(Mutex::new(None));

        let steps_for_transport = Arc::clone(&steps);
        let headers_for_transport = Arc::clone(&seen_headers);
        let timeout_for_transport = Arc::clone(&seen_timeout);
        let proxy_for_transport = Arc::clone(&seen_proxy);
        let transport: TransportFn = Arc::new(move |request: HttpRequest| {
            let steps = Arc::clone(&steps_for_transport);
            let seen_headers = Arc::clone(&headers_for_transport);
            let seen_timeout = Arc::clone(&timeout_for_transport);
            let seen_proxy = Arc::clone(&proxy_for_transport);
            futures_boxed::boxed(async move {
                *seen_headers.lock().unwrap() = Some(request.headers.clone());
                *seen_timeout.lock().unwrap() = Some(request.timeout_ms);
                *seen_proxy.lock().unwrap() = request.proxy.clone();
                // script is FIFO — take from the front
                let step = steps.lock().unwrap().first().cloned();
                if step.is_some() {
                    steps.lock().unwrap().remove(0);
                }
                let Some(step) = step else {
                    return Err(FetchFailure::InvalidInput(
                        "unexpected extra fetch call".to_string(),
                    ));
                };
                if let Some(throw) = step.get("throw") {
                    let message = str_field(throw, "message");
                    return Err(FetchFailure::Transport {
                        failure: rpi_ext_smart_fetch::http::TransportFailure::Other { message },
                        final_url: None,
                    });
                }
                let mut headers = std::collections::HashMap::new();
                for (key, value) in step
                    .get("headers")
                    .and_then(Value::as_object)
                    .into_iter()
                    .flatten()
                {
                    if let Some(value) = value.as_str() {
                        headers.insert(key.to_lowercase(), value.to_string());
                    }
                }
                Ok(HttpResponse {
                    final_url: request.url.clone(),
                    status: step.get("status").and_then(Value::as_u64).unwrap_or(200) as u16,
                    status_text: step
                        .get("statusText")
                        .and_then(Value::as_str)
                        .unwrap_or("OK")
                        .to_string(),
                    headers,
                    body: str_field(&step, "body"),
                })
            })
        });

        let pipeline = FetchPipeline {
            extractor: Box::new(scripted_extraction),
            transport,
        };
        let outcome = pipeline.fetch(&opts).await;
        let actual_result = match outcome {
            FetchOutcome::Result(result) => serde_json::to_value(&result).expect("serialize"),
            FetchOutcome::Error(error) => serde_json::to_value(&error).expect("serialize"),
        };
        let output = scenario.get("output").expect("output");
        let expected_result = output.get("result").cloned().unwrap_or(Value::Null);

        if SKIP_RESULT.contains(&name.as_str()) {
            // scope-exception cases still replay (no panic), just not asserted
            continue;
        }

        let mut actual_for_compare = actual_result.clone();
        if ASTRAL_VARIANT.contains(&name.as_str()) {
            // char-boundary truncation takes more characters than UTF-16
            // units: compare everything except the truncated content tail,
            // which is the declared drift sample.
            let expected_content = expected_result.get("content").and_then(Value::as_str);
            if let (Some(expected_content), Some(actual_content)) = (
                expected_content,
                actual_result.get("content").and_then(Value::as_str),
            ) {
                let common = expected_content
                    .char_indices()
                    .zip(actual_content.chars())
                    .take_while(|((_, expected_char), actual_char)| expected_char == actual_char)
                    .count();
                assert!(
                    common >= 3,
                    "{name}: astral prefix diverged unexpectedly: {expected_content:?} vs {actual_content:?}"
                );
                if let Some(object) = actual_for_compare.as_object_mut() {
                    object.insert("content".to_string(), json!("<astral-variant>"));
                }
                let mut expected_for_compare = expected_result.clone();
                if let Some(object) = expected_for_compare.as_object_mut() {
                    object.insert("content".to_string(), json!("<astral-variant>"));
                }
                if strip_nullish(actual_for_compare.clone())
                    != strip_nullish(expected_for_compare.clone())
                {
                    failures.push(format!(
                        "{name}: astral non-content fields mismatch\n  expected: {expected_for_compare}\n  actual:   {actual_for_compare}"
                    ));
                }
                continue;
            }
        }

        if strip_nullish(actual_result.clone()) != strip_nullish(expected_result.clone()) {
            failures.push(format!(
                "{name}: result mismatch\n  expected: {expected_result}\n  actual:   {actual_result}"
            ));
            continue;
        }

        // request assertions — only meaningful when a request was made
        // (upstream records nulls when URL validation rejected first)
        let expected_headers = output
            .get("requestHeadersSeen")
            .cloned()
            .unwrap_or(Value::Null);
        if expected_headers.is_null() {
            continue;
        }
        let actual_headers = seen_headers
            .lock()
            .unwrap()
            .clone()
            .map(|map| serde_json::to_value(map).unwrap_or(Value::Null))
            .unwrap_or(Value::Null);
        if strip_nullish(actual_headers.clone()) != strip_nullish(expected_headers.clone()) {
            failures.push(format!(
                "{name}: headers mismatch\n  expected: {expected_headers}\n  actual:   {actual_headers}"
            ));
        }
        let expected_timeout = output.get("requestTimeout").cloned().unwrap_or(Value::Null);
        let actual_timeout = seen_timeout.lock().unwrap().unwrap_or(0);
        if expected_timeout.as_u64() != Some(actual_timeout) {
            failures.push(format!(
                "{name}: timeout mismatch expected {expected_timeout} actual {actual_timeout}"
            ));
        }
        let expected_proxy = output.get("requestProxy").cloned().unwrap_or(Value::Null);
        let actual_proxy = seen_proxy
            .lock()
            .unwrap()
            .clone()
            .map(Value::String)
            .unwrap_or(Value::Null);
        if strip_nullish(expected_proxy.clone()) != strip_nullish(actual_proxy.clone()) {
            failures.push(format!(
                "{name}: proxy mismatch expected {expected_proxy} actual {actual_proxy}"
            ));
        }
        let expected_redirect = output
            .get("requestRedirect")
            .and_then(Value::as_str)
            .unwrap_or("follow");
        if expected_redirect != "follow" {
            failures.push(format!("{name}: redirect expected {expected_redirect}"));
        }
    }

    assert!(
        failures.is_empty(),
        "{} pipeline parity failures:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
