//! build.rs placeholder for the built-in model catalog pipeline (T03).
//!
//! The real generator reads models.dev data and applies the correction rules
//! of `packages/ai/scripts/generate-models.ts`; that pipeline and the remote
//! refresh land in T13/T14. For now this emits an empty `@generated` catalog
//! so the include mechanism is in place.

use std::path::PathBuf;

const GENERATED: &str = "\
// @generated by pir-ai build.rs — do not edit.
// Placeholder catalog (T03); real models.dev data lands in T13/T14.
pub static GENERATED_MODELS: &[crate::types::Model] = &[];
";

fn main() {
    // invariant: cargo always sets OUT_DIR for build scripts
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    let out_path = PathBuf::from(out_dir).join("models_generated.rs");
    // invariant: the cargo scratch dir is writable during the build
    std::fs::write(&out_path, GENERATED).expect("write generated models catalog");
    println!("cargo:rerun-if-changed=build.rs");
}
