//! build.rs — built-in model catalog pipeline (T13 W4).
//!
//! Reads the vendored provider catalog data in `src/providers/data/` (copied
//! verbatim from `external/pi/packages/ai/src/providers/data/`, first vendored
//! at pin 0.82.1 @ 2efa728 and verified byte-identical at 4181f66 / 0.84.1+
//! on the v0.11 bump — generatedAt 2026-07-30 predates both pins; read-only
//! generated data — never edit by hand, coding-standards
//! §3.2) and emits `models_generated.rs` into `OUT_DIR` with:
//!
//! - `CATALOG_PROVIDER_DATA`: `(provider_id, include_str!(json))` pairs, one
//!   per vendored `<provider>.json` (filename order, dotfiles skipped).
//! - `CATALOG_MANIFEST_JSON`: the vendored `.manifest.json` (schemaVersion /
//!   generatedAt / per-file sha256), parsed at runtime by `generated.rs`.
//!
//! The correction rules of upstream `packages/ai/scripts/generate-models.ts`
//! (compat deltas, thinkingLevelMap, pricing tiers, implied Kimi costs, …) are
//! already baked into the vendored JSONs: the upstream `*.models.ts` files are
//! generated pure re-exports (`flattenModelCatalog`), so the Rust side parses
//! the data as-is and applies nothing further.
//!
//! Refresh flow (manual, never at build time — builds stay offline):
//! `scripts/refresh-model-catalog.sh` re-vendors the JSONs from the pinned
//! upstream checkout after running its `generate-models.ts`; an upstream pin
//! bump requires an ADR (coding-standards §15.2).

use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir =
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo");
    let data_dir = Path::new(&manifest_dir).join("src/providers/data");
    // invariant: cargo always sets OUT_DIR for build scripts
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    let out_path = PathBuf::from(out_dir).join("models_generated.rs");

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    for entry in std::fs::read_dir(&data_dir).expect("read vendored catalog data dir") {
        let entry = entry.expect("read catalog data dir entry");
        let name = entry.file_name();
        let Some(name) = name.to_str() else { continue };
        // The dotfile `.manifest.json` is embedded separately below.
        if name.starts_with('.') || !name.ends_with(".json") {
            continue;
        }
        let provider = name.trim_end_matches(".json").to_owned();
        entries.push((provider, entry.path()));
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut generated = String::from(
        "// @generated by rpi-ai build.rs from src/providers/data/ — DO NOT EDIT.\n\
         // Vendored from external/pi/packages/ai/src/providers/data/ @ pi 0.82.1 (2efa728),\n\
         // verified byte-identical at 4181f66 / 0.84.1+ (v0.11).\n",
    );
    generated.push_str("\n/// `(provider_id, catalog JSON)` pairs, filename order.\n");
    generated.push_str("pub static CATALOG_PROVIDER_DATA: &[(&str, &str)] = &[\n");
    for (provider, path) in &entries {
        let path = path.to_str().expect("catalog data path is UTF-8");
        generated.push_str(&format!("    ({provider:?}, include_str!({path:?})),\n"));
        println!("cargo:rerun-if-changed={path}");
    }
    generated.push_str("];\n");

    let manifest_path = data_dir.join(".manifest.json");
    let manifest = manifest_path.to_str().expect("manifest path is UTF-8");
    generated.push_str(&format!(
        "\n/// Vendored `.manifest.json` (schemaVersion/generatedAt/per-file sha256).\n\
         pub static CATALOG_MANIFEST_JSON: &str = include_str!({manifest:?});\n"
    ));
    println!("cargo:rerun-if-changed={manifest}");

    // invariant: the cargo scratch dir is writable during the build
    std::fs::write(&out_path, generated).expect("write generated models catalog");
    println!("cargo:rerun-if-changed=build.rs");
}
