//! Port of `packages/ai/src/image-models.generated.ts` @ pi 0.82.1 (2efa728).
//!
//! The image-generation catalog (upstream `IMAGE_MODELS`), transcribed
//! structure-identically from the checked-in TS literal: one provider
//! (`openrouter`) with 40 image models. Upstream generates this file via
//! `scripts/generate-image-models.ts` (a dev-time OpenRouter catalog
//! fetch); the Rust side keeps the same checked-in-literal approach and
//! does not port the script (deviation D-036).

use std::sync::OnceLock;

use crate::types::{
    ImagesApiKind, ImagesModel, ImagesOutputModality, InputModality, ModelCost, ModelCostRates,
};

/// `IMAGE_MODELS` — image-generation catalog, keyed by provider id
/// (upstream `Object.entries(IMAGE_MODELS)` order). Built once on first
/// access (const literals cannot hold `String`/`Vec` values).
pub fn image_models() -> &'static [(&'static str, Vec<ImagesModel>)] {
    static CATALOG: OnceLock<Vec<(&'static str, Vec<ImagesModel>)>> = OnceLock::new();
    CATALOG.get_or_init(|| {
        vec![(
            "openrouter",
            vec![
                ImagesModel {
                    id: "black-forest-labs/flux.2-flex".to_owned(),
                    name: "Black Forest Labs: FLUX.2 Flex".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "black-forest-labs/flux.2-klein-4b".to_owned(),
                    name: "Black Forest Labs: FLUX.2 Klein 4B".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "black-forest-labs/flux.2-max".to_owned(),
                    name: "Black Forest Labs: FLUX.2 Max".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "black-forest-labs/flux.2-pro".to_owned(),
                    name: "Black Forest Labs: FLUX.2 Pro".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "bytedance-seed/seedream-4.5".to_owned(),
                    name: "ByteDance Seed: Seedream 4.5".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Image, InputModality::Text],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "google/gemini-2.5-flash-image".to_owned(),
                    name: "Google: Nano Banana (Gemini 2.5 Flash Image)".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Image, InputModality::Text],
                    output: vec![ImagesOutputModality::Image, ImagesOutputModality::Text],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.3,
                            output: 2.5,
                            cache_read: 0.03,
                            cache_write: 0.08333333333333334,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "google/gemini-3-pro-image".to_owned(),
                    name: "Google: Nano Banana Pro (Gemini 3 Pro Image)".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Image, InputModality::Text],
                    output: vec![ImagesOutputModality::Image, ImagesOutputModality::Text],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 2.0,
                            output: 12.0,
                            cache_read: 0.19999999999999998,
                            cache_write: 0.375,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "google/gemini-3-pro-image-preview".to_owned(),
                    name: "Google: Nano Banana Pro (Gemini 3 Pro Image Preview)".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Image, InputModality::Text],
                    output: vec![ImagesOutputModality::Image, ImagesOutputModality::Text],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 2.0,
                            output: 12.0,
                            cache_read: 0.19999999999999998,
                            cache_write: 0.375,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "google/gemini-3.1-flash-image".to_owned(),
                    name: "Google: Nano Banana 2 (Gemini 3.1 Flash Image)".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Image, InputModality::Text],
                    output: vec![ImagesOutputModality::Image, ImagesOutputModality::Text],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.5,
                            output: 3.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "google/gemini-3.1-flash-image-preview".to_owned(),
                    name: "Google: Nano Banana 2 (Gemini 3.1 Flash Image Preview)".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Image, InputModality::Text],
                    output: vec![ImagesOutputModality::Image, ImagesOutputModality::Text],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.5,
                            output: 3.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "google/gemini-3.1-flash-lite-image".to_owned(),
                    name: "Google: Nano Banana 2 Lite (Gemini 3.1 Flash Lite Image)".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Image, InputModality::Text],
                    output: vec![ImagesOutputModality::Image, ImagesOutputModality::Text],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.25,
                            output: 1.5,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "krea/krea-2-large".to_owned(),
                    name: "Krea: Krea 2 Large".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "krea/krea-2-medium".to_owned(),
                    name: "Krea: Krea 2 Medium".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "krea/krea-2-medium-turbo".to_owned(),
                    name: "Krea: Krea 2 Medium Turbo".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "microsoft/mai-image-2.5".to_owned(),
                    name: "Microsoft: MAI-Image-2.5".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 5.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "microsoft/mai-image-2.5-pro".to_owned(),
                    name: "Microsoft: MAI-Image-2.5 Pro".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 5.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "openai/gpt-5-image".to_owned(),
                    name: "OpenAI: GPT-5 Image".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Image, InputModality::Text],
                    output: vec![ImagesOutputModality::Image, ImagesOutputModality::Text],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 10.0,
                            output: 10.0,
                            cache_read: 1.25,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "openai/gpt-5-image-mini".to_owned(),
                    name: "OpenAI: GPT-5 Image Mini".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Image, InputModality::Text],
                    output: vec![ImagesOutputModality::Image, ImagesOutputModality::Text],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 2.5,
                            output: 2.0,
                            cache_read: 0.25,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "openai/gpt-5.4-image-2".to_owned(),
                    name: "OpenAI: GPT-5.4 Image 2".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Image, InputModality::Text],
                    output: vec![ImagesOutputModality::Image, ImagesOutputModality::Text],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 8.0,
                            output: 15.0,
                            cache_read: 2.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "openai/gpt-image-1".to_owned(),
                    name: "OpenAI: GPT Image 1".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 10.0,
                            output: 10.0,
                            cache_read: 1.25,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "openai/gpt-image-1-mini".to_owned(),
                    name: "OpenAI: GPT Image 1 Mini".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 2.5,
                            output: 2.5,
                            cache_read: 0.25,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "openai/gpt-image-2".to_owned(),
                    name: "OpenAI: GPT Image 2".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 8.0,
                            output: 8.0,
                            cache_read: 2.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "openrouter/auto".to_owned(),
                    name: "Auto Router".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Text, ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: -1000000.0,
                            output: -1000000.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "openrouter/auto-beta".to_owned(),
                    name: "Auto Router (Beta)".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Text, ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: -1000000.0,
                            output: -1000000.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "recraft/recraft-v3".to_owned(),
                    name: "Recraft: Recraft V3".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "recraft/recraft-v4".to_owned(),
                    name: "Recraft: Recraft V4".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "recraft/recraft-v4-pro".to_owned(),
                    name: "Recraft: Recraft V4 Pro".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "recraft/recraft-v4-pro-vector".to_owned(),
                    name: "Recraft: Recraft V4 Pro Vector".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "recraft/recraft-v4-vector".to_owned(),
                    name: "Recraft: Recraft V4 Vector".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "recraft/recraft-v4.1".to_owned(),
                    name: "Recraft: Recraft V4.1".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "recraft/recraft-v4.1-pro".to_owned(),
                    name: "Recraft: Recraft V4.1 Pro".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "recraft/recraft-v4.1-pro-vector".to_owned(),
                    name: "Recraft: Recraft V4.1 Pro Vector".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "recraft/recraft-v4.1-utility".to_owned(),
                    name: "Recraft: Recraft V4.1 Utility".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "recraft/recraft-v4.1-utility-pro".to_owned(),
                    name: "Recraft: Recraft V4.1 Utility Pro".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "recraft/recraft-v4.1-vector".to_owned(),
                    name: "Recraft: Recraft V4.1 Vector".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "sourceful/riverflow-v2-fast".to_owned(),
                    name: "Sourceful: Riverflow V2 Fast".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "sourceful/riverflow-v2-pro".to_owned(),
                    name: "Sourceful: Riverflow V2 Pro".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "sourceful/riverflow-v2.5-fast".to_owned(),
                    name: "Sourceful: Riverflow V2.5 Fast".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "sourceful/riverflow-v2.5-pro".to_owned(),
                    name: "Sourceful: Riverflow V2.5 Pro".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
                ImagesModel {
                    id: "x-ai/grok-imagine-image-quality".to_owned(),
                    name: "xAI: Grok Imagine Image Quality".to_owned(),
                    api: ImagesApiKind(ImagesApiKind::OPENROUTER_IMAGES.to_owned()),
                    provider: "openrouter".to_owned(),
                    base_url: "https://openrouter.ai/api/v1".to_owned(),
                    input: vec![InputModality::Text, InputModality::Image],
                    output: vec![ImagesOutputModality::Image],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    headers: None,
                },
            ],
        )]
    })
}
