//! Session entry serde skeleton (T01; behavior lands in T07/T16).
//!
//! Consolidates the entry types of
//! `packages/coding-agent/src/core/session-manager.ts` and
//! `packages/agent/src/harness/types.ts` @ pi 0.82.1 (2efa728) into a single
//! source shared by the `pir` main path and the `pir-agent` harness layer.
//!
//! Intentional differences (structural, wire-compatible):
//! - Upstream defines two near-identical entry type families (coding-agent
//!   `SessionEntry`, harness `SessionTreeEntry`). Rust has no structural
//!   typing, so both are unified here: one payload struct per entry type, one
//!   [`SessionEntry`] enum with all 11 variants (9 main-path +
//!   harness-only `active_tools_change` / `leaf`), plus [`SessionHeader`] and
//!   the [`FileEntry`] raw file union (requirements §6.2).
//! - `CompactionEntry` supports both persisted forms: the main-path
//!   `firstKeptEntryId` form and the harness self-contained `retainedTail`
//!   form (both fields optional on the type; ADR-0003 §1). Write discipline is
//!   enforced by the writers, not the type: the `pir` main path writes only
//!   `firstKeptEntryId` (pinned-version behavior); the harness may write
//!   either form.
//!
//! Field nullability mirrors upstream exactly: `parentId` / `leaf.targetId`
//! are `string | null` (always serialized, `null` when absent); fields typed
//! `... | undefined` upstream are omitted from JSON when `None`.

use pir_ai::types::Usage;
use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::messages::AgentMessage;

/// `CURRENT_SESSION_VERSION` (session-manager.ts).
pub const CURRENT_SESSION_VERSION: u32 = 3;

// ---------------------------------------------------------------------------
// Entry payload structs (shared base: id / parentId / timestamp)
// ---------------------------------------------------------------------------

/// `SessionMessageEntry`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MessageEntry {
    pub id: String,
    pub parent_id: Option<String>,
    pub timestamp: String,
    pub message: AgentMessage,
}

/// `ThinkingLevelChangeEntry`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThinkingLevelChangeEntry {
    pub id: String,
    pub parent_id: Option<String>,
    pub timestamp: String,
    pub thinking_level: String,
}

/// `ModelChangeEntry`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelChangeEntry {
    pub id: String,
    pub parent_id: Option<String>,
    pub timestamp: String,
    pub provider: String,
    pub model_id: String,
}

/// Harness-only `ActiveToolsChangeEntry` (harness/types.ts).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ActiveToolsChangeEntry {
    pub id: String,
    pub parent_id: Option<String>,
    pub timestamp: String,
    pub active_tool_names: Vec<String>,
}

/// `CompactionEntry` — both persisted forms (see file header note).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CompactionEntry {
    pub id: String,
    pub parent_id: Option<String>,
    pub timestamp: String,
    pub summary: String,
    /// Main-path form: id of the first entry kept after the cut point.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub first_kept_entry_id: Option<String>,
    pub tokens_before: u64,
    /// Harness form: self-contained retained tail messages.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub retained_tail: Option<Vec<AgentMessage>>,
    /// Extension-specific data (e.g. ArtifactIndex, version markers for
    /// structured compaction).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<Value>,
    /// Usage from the LLM call(s) that generated this summary, if available.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage: Option<Usage>,
    /// True if generated by an extension; undefined/false if pi-generated
    /// (backward compatible).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub from_hook: Option<bool>,
}

/// `BranchSummaryEntry`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BranchSummaryEntry {
    pub id: String,
    pub parent_id: Option<String>,
    pub timestamp: String,
    pub from_id: String,
    pub summary: String,
    /// Extension-specific data (not sent to LLM).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<Value>,
    /// Usage from the LLM call that generated this summary, if available.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage: Option<Usage>,
    /// True if generated by an extension, false if pi-generated.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub from_hook: Option<bool>,
}

/// `CustomEntry` — extension data persisting across session reloads.
/// Does NOT participate in LLM context (ignored by buildSessionContext).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CustomEntry {
    pub id: String,
    pub parent_id: Option<String>,
    pub timestamp: String,
    pub custom_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<Value>,
}

/// `CustomMessageEntry` — extension messages injected into LLM context
/// (converted to a user message in buildSessionContext).
///
/// `display` controls TUI rendering: false = hidden entirely; true = rendered
/// with distinct styling.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CustomMessageEntry {
    pub id: String,
    pub parent_id: Option<String>,
    pub timestamp: String,
    pub custom_type: String,
    /// Field-level correction vs the T01 skeleton: `#[serde(default)]` mirrors
    /// the upstream `entry.content ?? []` fallback in
    /// `sessionEntryToContextMessages` (session-manager.ts:398).
    #[serde(default)]
    pub content: pir_ai::types::UserContent,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<Value>,
    pub display: bool,
}

/// `LabelEntry` — user-defined bookmarks/markers on entries.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LabelEntry {
    pub id: String,
    pub parent_id: Option<String>,
    pub timestamp: String,
    pub target_id: String,
    /// `string | undefined` upstream: omitted from JSON when `None`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

/// `SessionInfoEntry` — session metadata (e.g. user-defined display name).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionInfoEntry {
    pub id: String,
    pub parent_id: Option<String>,
    pub timestamp: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// Harness-only `LeafEntry` — leaf moves are recorded by appending a `leaf`
/// record (parentId points at the old leaf, targetId at the new leaf) rather
/// than mutating in place; loaders replay all entries in order to rebuild the
/// leaf id (requirements §4.4).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LeafEntry {
    pub id: String,
    pub parent_id: Option<String>,
    pub timestamp: String,
    /// `string | null` upstream: always serialized.
    pub target_id: Option<String>,
}

// ---------------------------------------------------------------------------
// Unions
// ---------------------------------------------------------------------------

/// `SessionEntry` / harness `SessionTreeEntry` — entries returned by "read"
/// methods. The `type` tag literals match upstream exactly.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "snake_case",
    rename_all_fields = "camelCase"
)]
pub enum SessionEntry {
    Message(MessageEntry),
    ThinkingLevelChange(ThinkingLevelChangeEntry),
    ModelChange(ModelChangeEntry),
    ActiveToolsChange(ActiveToolsChangeEntry),
    Compaction(CompactionEntry),
    BranchSummary(BranchSummaryEntry),
    Custom(CustomEntry),
    CustomMessage(CustomMessageEntry),
    Label(LabelEntry),
    SessionInfo(SessionInfoEntry),
    Leaf(LeafEntry),
}

/// `SessionHeader` (session-manager.ts).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionHeader {
    /// Session format version; absent in v1 sessions.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<u32>,
    pub id: String,
    /// ISO timestamp.
    pub timestamp: String,
    /// Field-level correction vs the T01 skeleton: `#[serde(default)]` because
    /// old sessions predate the `cwd` field (upstream SessionInfo documents
    /// "Empty string for old sessions", session-manager.ts:625-628).
    #[serde(default)]
    pub cwd: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parent_session: Option<String>,
}

/// `FileEntry = SessionHeader | SessionEntry` — raw file line union.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "snake_case",
    rename_all_fields = "camelCase"
)]
pub enum FileEntry {
    Session(SessionHeader),
    Message(MessageEntry),
    ThinkingLevelChange(ThinkingLevelChangeEntry),
    ModelChange(ModelChangeEntry),
    ActiveToolsChange(ActiveToolsChangeEntry),
    Compaction(CompactionEntry),
    BranchSummary(BranchSummaryEntry),
    Custom(CustomEntry),
    CustomMessage(CustomMessageEntry),
    Label(LabelEntry),
    SessionInfo(SessionInfoEntry),
    Leaf(LeafEntry),
}

impl FileEntry {
    /// Convert into the read-side [`SessionEntry`] union; the header variant
    /// maps to `None` (headers are not tree entries).
    pub fn into_session_entry(self) -> Option<SessionEntry> {
        match self {
            FileEntry::Session(_) => None,
            FileEntry::Message(e) => Some(SessionEntry::Message(e)),
            FileEntry::ThinkingLevelChange(e) => Some(SessionEntry::ThinkingLevelChange(e)),
            FileEntry::ModelChange(e) => Some(SessionEntry::ModelChange(e)),
            FileEntry::ActiveToolsChange(e) => Some(SessionEntry::ActiveToolsChange(e)),
            FileEntry::Compaction(e) => Some(SessionEntry::Compaction(e)),
            FileEntry::BranchSummary(e) => Some(SessionEntry::BranchSummary(e)),
            FileEntry::Custom(e) => Some(SessionEntry::Custom(e)),
            FileEntry::CustomMessage(e) => Some(SessionEntry::CustomMessage(e)),
            FileEntry::Label(e) => Some(SessionEntry::Label(e)),
            FileEntry::SessionInfo(e) => Some(SessionEntry::SessionInfo(e)),
            FileEntry::Leaf(e) => Some(SessionEntry::Leaf(e)),
        }
    }
}

impl SessionEntry {
    /// Upstream `entry.type` literal.
    pub fn type_tag(&self) -> &'static str {
        match self {
            SessionEntry::Message(_) => "message",
            SessionEntry::ThinkingLevelChange(_) => "thinking_level_change",
            SessionEntry::ModelChange(_) => "model_change",
            SessionEntry::ActiveToolsChange(_) => "active_tools_change",
            SessionEntry::Compaction(_) => "compaction",
            SessionEntry::BranchSummary(_) => "branch_summary",
            SessionEntry::Custom(_) => "custom",
            SessionEntry::CustomMessage(_) => "custom_message",
            SessionEntry::Label(_) => "label",
            SessionEntry::SessionInfo(_) => "session_info",
            SessionEntry::Leaf(_) => "leaf",
        }
    }

    /// `entry.id`.
    pub fn id(&self) -> &str {
        match self {
            SessionEntry::Message(e) => &e.id,
            SessionEntry::ThinkingLevelChange(e) => &e.id,
            SessionEntry::ModelChange(e) => &e.id,
            SessionEntry::ActiveToolsChange(e) => &e.id,
            SessionEntry::Compaction(e) => &e.id,
            SessionEntry::BranchSummary(e) => &e.id,
            SessionEntry::Custom(e) => &e.id,
            SessionEntry::CustomMessage(e) => &e.id,
            SessionEntry::Label(e) => &e.id,
            SessionEntry::SessionInfo(e) => &e.id,
            SessionEntry::Leaf(e) => &e.id,
        }
    }

    /// `entry.parentId`.
    pub fn parent_id(&self) -> Option<&str> {
        match self {
            SessionEntry::Message(e) => e.parent_id.as_deref(),
            SessionEntry::ThinkingLevelChange(e) => e.parent_id.as_deref(),
            SessionEntry::ModelChange(e) => e.parent_id.as_deref(),
            SessionEntry::ActiveToolsChange(e) => e.parent_id.as_deref(),
            SessionEntry::Compaction(e) => e.parent_id.as_deref(),
            SessionEntry::BranchSummary(e) => e.parent_id.as_deref(),
            SessionEntry::Custom(e) => e.parent_id.as_deref(),
            SessionEntry::CustomMessage(e) => e.parent_id.as_deref(),
            SessionEntry::Label(e) => e.parent_id.as_deref(),
            SessionEntry::SessionInfo(e) => e.parent_id.as_deref(),
            SessionEntry::Leaf(e) => e.parent_id.as_deref(),
        }
    }

    /// `entry.timestamp` (ISO string).
    pub fn timestamp(&self) -> &str {
        match self {
            SessionEntry::Message(e) => &e.timestamp,
            SessionEntry::ThinkingLevelChange(e) => &e.timestamp,
            SessionEntry::ModelChange(e) => &e.timestamp,
            SessionEntry::ActiveToolsChange(e) => &e.timestamp,
            SessionEntry::Compaction(e) => &e.timestamp,
            SessionEntry::BranchSummary(e) => &e.timestamp,
            SessionEntry::Custom(e) => &e.timestamp,
            SessionEntry::CustomMessage(e) => &e.timestamp,
            SessionEntry::Label(e) => &e.timestamp,
            SessionEntry::SessionInfo(e) => &e.timestamp,
            SessionEntry::Leaf(e) => &e.timestamp,
        }
    }
}

#[cfg(test)]
mod tests {
    use pir_ai::types::{AssistantRole, StopReason, Usage};
    use serde_json::{json, Value};

    use super::*;
    use crate::messages::{BashExecutionMessage, BashExecutionRole};

    fn to_json<T: Serialize>(v: &T) -> String {
        serde_json::to_string(v).expect("serialization must succeed")
    }

    fn assistant_agent_msg() -> AgentMessage {
        AgentMessage::Assistant(pir_ai::types::AssistantMessage {
            role: AssistantRole::Assistant,
            content: vec![],
            api: "anthropic-messages".into(),
            provider: "anthropic".to_owned(),
            model: "m".to_owned(),
            response_model: None,
            response_id: None,
            diagnostics: None,
            usage: Usage::default(),
            stop_reason: StopReason::Stop,
            error_message: None,
            timestamp: 0,
        })
    }

    #[test]
    fn session_header_shape() {
        let header = SessionHeader {
            version: Some(CURRENT_SESSION_VERSION),
            id: "s1".to_owned(),
            timestamp: "2026-07-30T00:00:00.000Z".to_owned(),
            cwd: "/repo".to_owned(),
            parent_session: None,
        };
        let entry = FileEntry::Session(header.clone());
        assert_eq!(
            to_json(&entry),
            r#"{"type":"session","version":3,"id":"s1","timestamp":"2026-07-30T00:00:00.000Z","cwd":"/repo"}"#
        );
        let back: FileEntry = serde_json::from_str(&to_json(&entry)).expect("roundtrip");
        assert_eq!(back, entry);

        // v1 sessions have no `version` key; `parentSession` appears when set.
        let v1 = SessionHeader {
            version: None,
            parent_session: Some("parent".to_owned()),
            ..header
        };
        let v: Value = serde_json::from_str(&to_json(&FileEntry::Session(v1))).expect("parse");
        assert!(v.get("version").is_none());
        assert_eq!(v["parentSession"], json!("parent"));
    }

    #[test]
    fn message_entry_shape_with_null_parent() {
        let entry = FileEntry::Message(MessageEntry {
            id: "e1".to_owned(),
            parent_id: None,
            timestamp: "2026-07-30T00:00:01.000Z".to_owned(),
            message: assistant_agent_msg(),
        });
        let v: Value = serde_json::from_str(&to_json(&entry)).expect("parse");
        assert_eq!(v["type"], json!("message"));
        // `parentId: string | null` upstream: always serialized.
        assert!(v.as_object().expect("object").contains_key("parentId"));
        assert_eq!(v["parentId"], Value::Null);
        assert_eq!(v["message"]["role"], json!("assistant"));
        let back: FileEntry = serde_json::from_str(&to_json(&entry)).expect("roundtrip");
        assert_eq!(back, entry);
    }

    #[test]
    fn compaction_entry_first_kept_entry_id_form() {
        // Main-path form (coding-agent writes/reads this).
        let entry = CompactionEntry {
            id: "c1".to_owned(),
            parent_id: Some("e1".to_owned()),
            timestamp: "t".to_owned(),
            summary: "summary".to_owned(),
            first_kept_entry_id: Some("e9".to_owned()),
            tokens_before: 12_345,
            retained_tail: None,
            details: None,
            usage: None,
            from_hook: None,
        };
        assert_eq!(
            to_json(&FileEntry::Compaction(entry.clone())),
            r#"{"type":"compaction","id":"c1","parentId":"e1","timestamp":"t","summary":"summary","firstKeptEntryId":"e9","tokensBefore":12345}"#
        );
        let back: FileEntry = serde_json::from_str(&to_json(&FileEntry::Compaction(entry.clone())))
            .expect("roundtrip");
        assert_eq!(back, FileEntry::Compaction(entry));
    }

    #[test]
    fn compaction_entry_retained_tail_form() {
        // Harness self-contained form (read+write support, ADR-0003 §1).
        let entry = CompactionEntry {
            id: "c2".to_owned(),
            parent_id: None,
            timestamp: "t".to_owned(),
            summary: "summary".to_owned(),
            first_kept_entry_id: None,
            tokens_before: 100,
            retained_tail: Some(vec![assistant_agent_msg()]),
            details: Some(json!({"version": 1})),
            usage: Some(Usage::default()),
            from_hook: Some(true),
        };
        let v: Value =
            serde_json::from_str(&to_json(&FileEntry::Compaction(entry.clone()))).expect("parse");
        assert!(v.get("firstKeptEntryId").is_none());
        assert_eq!(v["retainedTail"][0]["role"], json!("assistant"));
        assert_eq!(v["details"], json!({"version": 1}));
        assert_eq!(v["fromHook"], json!(true));
        assert!(v.get("usage").is_some());
        let back: FileEntry = serde_json::from_str(&to_json(&FileEntry::Compaction(entry.clone())))
            .expect("roundtrip");
        assert_eq!(back, FileEntry::Compaction(entry));
    }

    #[test]
    fn remaining_entry_type_shapes() {
        let base =
            (|| ("e".to_owned(), None, "t".to_owned())) as fn() -> (String, Option<String>, String);
        let (id, parent_id, timestamp) = base();

        let thinking = FileEntry::ThinkingLevelChange(ThinkingLevelChangeEntry {
            id: id.clone(),
            parent_id: parent_id.clone(),
            timestamp: timestamp.clone(),
            thinking_level: "high".to_owned(),
        });
        assert_eq!(
            to_json(&thinking),
            r#"{"type":"thinking_level_change","id":"e","parentId":null,"timestamp":"t","thinkingLevel":"high"}"#
        );

        let model = FileEntry::ModelChange(ModelChangeEntry {
            id: id.clone(),
            parent_id: parent_id.clone(),
            timestamp: timestamp.clone(),
            provider: "anthropic".to_owned(),
            model_id: "claude-x".to_owned(),
        });
        assert_eq!(
            to_json(&model),
            r#"{"type":"model_change","id":"e","parentId":null,"timestamp":"t","provider":"anthropic","modelId":"claude-x"}"#
        );

        let branch = FileEntry::BranchSummary(BranchSummaryEntry {
            id: id.clone(),
            parent_id: parent_id.clone(),
            timestamp: timestamp.clone(),
            from_id: "e0".to_owned(),
            summary: "s".to_owned(),
            details: None,
            usage: None,
            from_hook: Some(false),
        });
        assert_eq!(
            to_json(&branch),
            r#"{"type":"branch_summary","id":"e","parentId":null,"timestamp":"t","fromId":"e0","summary":"s","fromHook":false}"#
        );

        let custom = FileEntry::Custom(CustomEntry {
            id: id.clone(),
            parent_id: parent_id.clone(),
            timestamp: timestamp.clone(),
            custom_type: "artifact-index".to_owned(),
            data: Some(json!({"n": 1})),
        });
        assert_eq!(
            to_json(&custom),
            r#"{"type":"custom","id":"e","parentId":null,"timestamp":"t","customType":"artifact-index","data":{"n":1}}"#
        );

        let custom_message = FileEntry::CustomMessage(CustomMessageEntry {
            id: id.clone(),
            parent_id: parent_id.clone(),
            timestamp: timestamp.clone(),
            custom_type: "note".to_owned(),
            content: pir_ai::types::UserContent::Text("hello".to_owned()),
            details: None,
            display: false,
        });
        assert_eq!(
            to_json(&custom_message),
            r#"{"type":"custom_message","id":"e","parentId":null,"timestamp":"t","customType":"note","content":"hello","display":false}"#
        );

        // Label: `label: string | undefined` -> key omitted when None.
        let label_cleared = FileEntry::Label(LabelEntry {
            id: id.clone(),
            parent_id: parent_id.clone(),
            timestamp: timestamp.clone(),
            target_id: "e1".to_owned(),
            label: None,
        });
        assert_eq!(
            to_json(&label_cleared),
            r#"{"type":"label","id":"e","parentId":null,"timestamp":"t","targetId":"e1"}"#
        );
        let label_set = FileEntry::Label(LabelEntry {
            id: id.clone(),
            parent_id: parent_id.clone(),
            timestamp: timestamp.clone(),
            target_id: "e1".to_owned(),
            label: Some("bookmark".to_owned()),
        });
        assert_eq!(
            to_json(&label_set),
            r#"{"type":"label","id":"e","parentId":null,"timestamp":"t","targetId":"e1","label":"bookmark"}"#
        );

        let info = FileEntry::SessionInfo(SessionInfoEntry {
            id: id.clone(),
            parent_id: parent_id.clone(),
            timestamp: timestamp.clone(),
            name: Some("my session".to_owned()),
        });
        assert_eq!(
            to_json(&info),
            r#"{"type":"session_info","id":"e","parentId":null,"timestamp":"t","name":"my session"}"#
        );

        for entry in [
            thinking,
            model,
            branch,
            custom,
            custom_message,
            label_cleared,
            label_set,
            info,
        ] {
            let back: FileEntry = serde_json::from_str(&to_json(&entry)).expect("roundtrip");
            assert_eq!(back, entry);
        }
    }

    #[test]
    fn harness_only_entry_shapes() {
        let active_tools = FileEntry::ActiveToolsChange(ActiveToolsChangeEntry {
            id: "a1".to_owned(),
            parent_id: None,
            timestamp: "t".to_owned(),
            active_tool_names: vec!["read".to_owned(), "bash".to_owned()],
        });
        assert_eq!(
            to_json(&active_tools),
            r#"{"type":"active_tools_change","id":"a1","parentId":null,"timestamp":"t","activeToolNames":["read","bash"]}"#
        );

        // Leaf: `targetId: string | null` upstream -> always serialized.
        let leaf_null = FileEntry::Leaf(LeafEntry {
            id: "l1".to_owned(),
            parent_id: Some("l0".to_owned()),
            timestamp: "t".to_owned(),
            target_id: None,
        });
        assert_eq!(
            to_json(&leaf_null),
            r#"{"type":"leaf","id":"l1","parentId":"l0","timestamp":"t","targetId":null}"#
        );
        let leaf_set = FileEntry::Leaf(LeafEntry {
            id: "l2".to_owned(),
            parent_id: Some("l1".to_owned()),
            timestamp: "t".to_owned(),
            target_id: Some("e3".to_owned()),
        });

        for entry in [active_tools, leaf_null, leaf_set] {
            let back: FileEntry = serde_json::from_str(&to_json(&entry)).expect("roundtrip");
            assert_eq!(back, entry);
        }

        // The SessionEntry read-side union covers all 11 entry variants
        // (header excluded).
        let entry = SessionEntry::ActiveToolsChange(ActiveToolsChangeEntry {
            id: "a2".to_owned(),
            parent_id: None,
            timestamp: "t".to_owned(),
            active_tool_names: vec![],
        });
        let back: SessionEntry = serde_json::from_str(&to_json(&entry)).expect("roundtrip");
        assert_eq!(back, entry);
    }

    #[test]
    fn message_entry_with_custom_message_payload() {
        // A message entry whose message is a bashExecution custom message
        // (produced by the `!` command) roundtrips intact.
        let entry = FileEntry::Message(MessageEntry {
            id: "m1".to_owned(),
            parent_id: None,
            timestamp: "t".to_owned(),
            message: AgentMessage::BashExecution(BashExecutionMessage {
                role: BashExecutionRole::BashExecution,
                command: "pwd".to_owned(),
                output: "/repo".to_owned(),
                exit_code: Some(0),
                cancelled: false,
                truncated: false,
                full_output_path: None,
                timestamp: 1,
                exclude_from_context: None,
            }),
        });
        let back: FileEntry = serde_json::from_str(&to_json(&entry)).expect("roundtrip");
        assert_eq!(back, entry);
    }
}
