//! Golden parity: 6-source config discovery + merge (FR-P0-01, design §5.1).
//!
//! `fixtures/config_merge_cases.json` is generated by executing the pinned
//! upstream `config.ts` `loadMcpConfig` @ 3d953f90
//! (`scripts/gen-mcp-adapter-fixtures.mjs`) against sandboxed config files —
//! the expected merged configs ARE upstream outputs. The rpi side writes the
//! same layer contents to the ADR-0001-mapped paths (`pi-global` ->
//! `~/.rpi/agent/mcp.json`, `pi-project` -> `<cwd>/.rpi/mcp.json`).
//!
//! One test function on purpose: cases mutate process env (`HOME`,
//! `RPI_CODING_AGENT_DIR`), and Rust runs tests in-process.

use std::path::{Path, PathBuf};

use rpi_ext_mcp_adapter::config::load_mcp_config;
use rpi_ext_mcp_adapter::metadata::{McpConfig, ServerEntry};
use serde_json::{Map, Value};

/// Layer -> rpi-side path (ADR-0001 mapping of the upstream layer layout
/// recorded in the generator script).
fn layer_path(layer: &str, home: &Path, project: &Path) -> PathBuf {
    match layer {
        "shared-global" => home.join(".config/mcp/mcp.json"),
        "agents-global" => home.join(".agents/mcp.json"),
        "agents-nested-global" => home.join(".agents/mcp/mcp.json"),
        "pi-global" => home.join(".rpi/agent/mcp.json"),
        "shared-project" => project.join(".mcp.json"),
        "pi-project" => project.join(".rpi/mcp.json"),
        other => panic!("unknown layer {other}"),
    }
}

fn config_to_value(config: &McpConfig) -> Value {
    let mut servers = Map::new();
    for (name, entry) in &config.mcp_servers {
        servers.insert(name.clone(), Value::Object(entry.as_map().clone()));
    }
    let mut out = Map::new();
    out.insert("mcpServers".to_string(), Value::Object(servers));
    if let Some(settings) = &config.settings {
        out.insert("settings".to_string(), Value::Object(settings.clone()));
    }
    if let Some(imports) = &config.imports {
        out.insert(
            "imports".to_string(),
            Value::Array(imports.iter().map(|i| Value::String(i.clone())).collect()),
        );
    }
    Value::Object(out)
}

#[test]
fn config_merge_matches_upstream_load_mcp_config() {
    let fixture: Value = serde_json::from_str(include_str!("fixtures/config_merge_cases.json"))
        .expect("fixture parses");
    let saved_home = std::env::var_os("HOME");
    let saved_agent_dir = std::env::var_os("RPI_CODING_AGENT_DIR");

    let run = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        for (index, case) in fixture["cases"]
            .as_array()
            .expect("cases")
            .iter()
            .enumerate()
        {
            let name = case["name"].as_str().unwrap_or_default();
            let sandbox = std::env::temp_dir().join(format!(
                "rpi-mcp-merge-test-{}-{}",
                std::process::id(),
                index
            ));
            let home = sandbox.join("home");
            let project = sandbox.join("proj");
            std::fs::create_dir_all(&home).expect("home dir");
            std::fs::create_dir_all(&project).expect("project dir");

            if let Some(layers) = case["layers"].as_object() {
                for (layer, content) in layers {
                    let path = layer_path(layer, &home, &project);
                    std::fs::create_dir_all(path.parent().expect("layer parent")).expect("mkdir");
                    std::fs::write(
                        &path,
                        format!(
                            "{}\n",
                            serde_json::to_string_pretty(content).unwrap_or_default()
                        ),
                    )
                    .expect("write layer");
                }
            }
            if let Some(raw_layers) = case["rawLayers"].as_object() {
                for (layer, raw) in raw_layers {
                    let path = layer_path(layer, &home, &project);
                    std::fs::create_dir_all(path.parent().expect("layer parent")).expect("mkdir");
                    std::fs::write(&path, raw.as_str().unwrap_or_default())
                        .expect("write raw layer");
                }
            }

            std::env::set_var("HOME", &home);
            std::env::remove_var("RPI_CODING_AGENT_DIR");

            let merged = load_mcp_config(None, &project);
            let actual = config_to_value(&merged);
            let expected = &case["expected"];
            assert_eq!(&actual, expected, "merged config diverged for case {name}");

            // Server key order is part of the fold semantics (JS object
            // insertion order) — check it separately from Value equality.
            let actual_order: Vec<&String> = merged.mcp_servers.keys().collect();
            let expected_order: Vec<&str> = expected["mcpServers"]
                .as_object()
                .map(|m| m.keys().map(String::as_str).collect())
                .unwrap_or_default();
            assert_eq!(
                actual_order.iter().map(|s| s.as_str()).collect::<Vec<_>>(),
                expected_order,
                "server key order diverged for case {name}"
            );

            std::fs::remove_dir_all(&sandbox).expect("cleanup");
        }
    }));

    match saved_home {
        Some(home) => std::env::set_var("HOME", home),
        None => std::env::remove_var("HOME"),
    }
    match saved_agent_dir {
        Some(dir) => std::env::set_var("RPI_CODING_AGENT_DIR", dir),
        None => std::env::remove_var("RPI_CODING_AGENT_DIR"),
    }
    run.expect("config merge comparison panicked");
}

/// Direct unit-level cross-check that `ServerEntry` wraps raw JSON without
/// dropping unknown keys (the merge layer's fidelity precondition).
#[test]
fn server_entry_preserves_unknown_keys() {
    let raw = serde_json::json!({ "command": "node", "futureField": { "x": 1 } });
    let entry = ServerEntry(raw.as_object().cloned().unwrap_or_default());
    assert_eq!(
        entry.get("futureField"),
        Some(&serde_json::json!({ "x": 1 }))
    );
}
