//! Dual-direction truncation golden (R7.2.10.2 / #500): the plugin-side
//! `truncate::truncate_head` must be BYTE-IDENTICAL to the host
//! implementation. The vectors in `fixtures/truncation_cases.json` are
//! generated by running the HOST `crates/rpi/src/tools/truncate.rs`
//! directly (see the fixture's provenance) — asserting against the same
//! frozen vectors from both sides gives the host→plugin and plugin→host
//! directions of the parity matrix. The L0 boundary forbids a test-time
//! dependency on the `rpi` crate, hence the vector file.

use rpi_ext_mcp_adapter::truncate::{truncate_head, TruncateOptions, TruncatedBy};
use serde_json::Value;

fn sha256_hex(data: &[u8]) -> String {
    use sha2::Digest;
    let digest = sha2::Sha256::digest(data);
    digest.iter().map(|b| format!("{b:02x}")).collect()
}

#[test]
fn truncate_head_matches_host_vectors_byte_for_byte() {
    let raw = include_str!("fixtures/truncation_cases.json");
    let fixture: Value = serde_json::from_str(raw).expect("fixture parses");
    let cases = fixture["cases"].as_array().expect("cases");
    assert!(cases.len() >= 20, "expected the full adversarial set");

    for case in cases {
        let name = case["name"].as_str().expect("name");
        let max_bytes = case["maxBytes"].as_u64().expect("maxBytes") as usize;
        let max_lines = case["maxLines"].as_u64().expect("maxLines") as usize;
        let expected = &case["expected"];
        let content = match case["content"].as_str() {
            // Small inputs are stored verbatim.
            Some(content) => content.to_string(),
            // Huge inputs (the 300 KiB line) are stored as sha256 only —
            // reconstruct deterministically from the case family.
            None => "x".repeat(300_000),
        };

        let result = truncate_head(
            &content,
            Some(TruncateOptions {
                max_lines,
                max_bytes,
            }),
        );

        // Byte-level content parity (full content when stored, digest for
        // the huge case).
        match expected["content"].as_str() {
            Some(expected_content) => assert_eq!(
                result.content, expected_content,
                "{name}: content must be byte-identical"
            ),
            None => {
                let digest = expected["expectedContentSha256"]
                    .as_str()
                    .expect("digest for huge case");
                assert_eq!(
                    sha256_hex(result.content.as_bytes()),
                    digest,
                    "{name}: content digest must match the host"
                );
            }
        }
        assert_eq!(
            result.truncated,
            expected["truncated"].as_bool().expect("truncated"),
            "{name}"
        );
        assert_eq!(
            result.truncated_by.map(|t| match t {
                TruncatedBy::Lines => "lines",
                TruncatedBy::Bytes => "bytes",
            }),
            expected["truncatedBy"].as_str(),
            "{name}"
        );
        let got = serde_json::json!({
            "totalLines": result.total_lines,
            "totalBytes": result.total_bytes,
            "outputLines": result.output_lines,
            "outputBytes": result.output_bytes,
            "lastLinePartial": result.last_line_partial,
            "firstLineExceedsLimit": result.first_line_exceeds_limit,
            "maxLines": result.max_lines,
            "maxBytes": result.max_bytes,
        });
        for field in [
            "totalLines",
            "totalBytes",
            "outputLines",
            "outputBytes",
            "lastLinePartial",
            "firstLineExceedsLimit",
            "maxLines",
            "maxBytes",
        ] {
            assert_eq!(&got[field], &expected[field], "{name}: {field}");
        }
    }
}
