//! Golden parity: search scoring / ranking / pagination / suggestions
//! (FR-P0-04 pure part, design §5.1).
//!
//! `fixtures/search_cases.json` is generated by executing the pinned
//! upstream `search-ranking.ts` @ 3d953f90
//! (`scripts/gen-mcp-adapter-fixtures.mjs`) — the expected scores and order
//! ARE the upstream outputs.

use rpi_ext_mcp_adapter::metadata::{McpConfig, ServerEntry, ToolMetadata};
use rpi_ext_mcp_adapter::search::{
    paginate, rank_suggestions, rank_tool_matches, score_tool_match, SearchState,
};
use serde_json::Value;

struct FixtureState {
    config: McpConfig,
    tool_metadata: Vec<(String, Vec<ToolMetadata>)>,
}

fn build_state(fixture: &Value) -> FixtureState {
    let mut config = McpConfig::default();
    let mut tool_metadata = Vec::new();
    for server in fixture["state"]["servers"].as_array().expect("servers") {
        let name = server["name"].as_str().expect("server name").to_string();
        let definition = ServerEntry(
            server["definition"]
                .as_object()
                .cloned()
                .unwrap_or_default(),
        );
        config.mcp_servers.insert(name.clone(), definition);
        let tools = server["tools"]
            .as_array()
            .expect("tools")
            .iter()
            .map(|t| ToolMetadata {
                name: t["name"].as_str().unwrap_or_default().to_string(),
                original_name: t["originalName"].as_str().unwrap_or_default().to_string(),
                description: t["description"].as_str().unwrap_or_default().to_string(),
                ..Default::default()
            })
            .collect();
        tool_metadata.push((name, tools));
    }
    config.settings = Some(
        serde_json::json!({ "toolPrefix": fixture["state"]["globalPrefix"].as_str().unwrap_or("server") })
            .as_object()
            .cloned()
            .unwrap_or_default(),
    );
    FixtureState {
        config,
        tool_metadata,
    }
}

#[test]
fn search_matches_upstream_scores_and_ordering() {
    let fixture: Value =
        serde_json::from_str(include_str!("fixtures/search_cases.json")).expect("fixture parses");
    let state = build_state(&fixture);
    let search_state = SearchState {
        config: &state.config,
        tool_metadata: &state.tool_metadata,
    };

    // Exact score parity per tool (including None for non-matches).
    for case in fixture["score"].as_array().expect("score cases") {
        let tool = ToolMetadata {
            name: case["tool"].as_str().unwrap_or_default().to_string(),
            original_name: case["tool"].as_str().unwrap_or_default().to_string(),
            description: case["description"].as_str().unwrap_or_default().to_string(),
            ..Default::default()
        };
        let keywords: Option<Vec<String>> = case["keywords"].as_array().map(|a| {
            a.iter()
                .filter_map(Value::as_str)
                .map(str::to_string)
                .collect()
        });
        let actual = score_tool_match(
            &tool,
            case["server"].as_str().unwrap_or_default(),
            case["query"].as_str().unwrap_or_default(),
            keywords.as_deref(),
        );
        let expected = case["expected"].as_i64();
        assert_eq!(actual, expected, "scoreToolMatch diverged: {case}");
    }

    // Full ranking parity (ordered server/tool/score triples).
    for case in fixture["rank"].as_array().expect("rank cases") {
        let matches = rank_tool_matches(
            &search_state,
            case["query"].as_str().unwrap_or_default(),
            case["server"].as_str(),
            case["includeKeywords"].as_bool().unwrap_or(true),
        );
        let actual: Vec<(String, String, i64)> = matches
            .iter()
            .map(|m| (m.server.clone(), m.tool.name.clone(), m.score))
            .collect();
        let expected: Vec<(String, String, i64)> = case["expected"]
            .as_array()
            .expect("expected array")
            .iter()
            .map(|m| {
                (
                    m["server"].as_str().unwrap_or_default().to_string(),
                    m["tool"].as_str().unwrap_or_default().to_string(),
                    m["score"].as_i64().unwrap_or_default(),
                )
            })
            .collect();
        assert_eq!(actual, expected, "rankToolMatches diverged: {case}");
    }

    // Pagination parity.
    for case in fixture["paginate"].as_array().expect("paginate cases") {
        let items: Vec<String> = case["items"]
            .as_array()
            .map(|a| {
                a.iter()
                    .filter_map(Value::as_str)
                    .map(str::to_string)
                    .collect()
            })
            .unwrap_or_default();
        let page = paginate(
            &items,
            case["offset"].as_i64().unwrap_or_default(),
            case["limit"].as_i64().unwrap_or_default(),
        );
        let expected = &case["expected"];
        let expected_items: Vec<String> = expected["items"]
            .as_array()
            .map(|a| {
                a.iter()
                    .filter_map(Value::as_str)
                    .map(str::to_string)
                    .collect()
            })
            .unwrap_or_default();
        assert_eq!(page.items, expected_items, "paginate items: {case}");
        assert_eq!(
            page.total as u64,
            expected["total"].as_u64().unwrap_or_default(),
            "paginate total: {case}"
        );
        assert_eq!(
            page.has_more,
            expected["hasMore"].as_bool().unwrap_or_default(),
            "paginate hasMore: {case}"
        );
        let expected_next = expected["nextOffset"].as_u64().map(|v| v as usize);
        assert_eq!(
            page.next_offset, expected_next,
            "paginate nextOffset: {case}"
        );
    }

    // Suggestion parity.
    for case in fixture["suggestions"].as_array().expect("suggestion cases") {
        let actual = rank_suggestions(
            &search_state,
            case["name"].as_str().unwrap_or_default(),
            case["limit"].as_u64().unwrap_or(5) as usize,
        );
        let expected: Vec<&str> = case["expected"]
            .as_array()
            .map(|a| a.iter().filter_map(Value::as_str).collect())
            .unwrap_or_default();
        assert_eq!(actual, expected, "rankSuggestions diverged: {case}");
    }
}
