//! Golden parity: ts-shape rendering (FR-P0-05, design §5.1).
//!
//! `fixtures/tsshape_cases.json` is generated by executing the pinned
//! upstream `ts-shape.ts` @ 3d953f90 (`scripts/gen-mcp-adapter-fixtures.mjs`)
//! — the expectations ARE the upstream outputs, byte for byte.

use rpi_ext_mcp_adapter::tsshape::render_ts_shape;
use serde_json::Value;

#[test]
fn tsshape_matches_upstream_byte_for_byte() {
    let fixture: Value =
        serde_json::from_str(include_str!("fixtures/tsshape_cases.json")).expect("fixture parses");
    let cases = fixture["cases"].as_array().expect("cases array");
    assert!(cases.len() >= 30, "expected the full generated case set");
    for case in cases {
        let name = case["name"].as_str().expect("case name");
        let expected = case["expected"].as_str(); // null -> None
        let actual = render_ts_shape(&case["input"]);
        assert_eq!(
            actual.as_deref(),
            expected,
            "ts-shape case {name:?} diverged from upstream"
        );
    }
}
