//! Golden parity: `computeServerHash` / `stableStringify` (FR-P0-10, design
//! §5.1).
//!
//! `fixtures/config_hash_cases.json` is generated by executing the pinned
//! upstream `metadata-cache.ts` @ 3d953f90
//! (`scripts/gen-mcp-adapter-fixtures.mjs`) — the expected sha256 values ARE
//! the upstream digests (cross-implementation vector parity).
//!
//! One test function on purpose: cases mutate process env
//! (`RPI_MCP_FIXTURE_*` / `HOME`), and Rust runs tests in-process.

use rpi_ext_mcp_adapter::cache::compute_server_hash;
use rpi_ext_mcp_adapter::metadata::ServerEntry;
use serde_json::Value;

#[test]
fn config_hash_matches_upstream_sha256_vectors() {
    let fixture: Value = serde_json::from_str(include_str!("fixtures/config_hash_cases.json"))
        .expect("fixture parses");
    let saved_home = std::env::var_os("HOME");
    let saved_fixture_vars: Vec<String> = std::env::vars()
        .map(|(k, _)| k)
        .filter(|k| k.starts_with("RPI_MCP_FIXTURE_"))
        .collect();

    let mut hashes: Vec<(String, String)> = Vec::new();
    let run = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        for case in fixture["cases"].as_array().expect("cases") {
            // Clean slate for the fixture-controlled variables.
            for key in [
                "RPI_MCP_FIXTURE_TOKEN",
                "RPI_MCP_FIXTURE_HOST",
                "RPI_MCP_FIXTURE_DEFINITELY_UNSET",
            ] {
                std::env::remove_var(key);
            }
            let env = case["env"].as_object().cloned().unwrap_or_default();
            match env.get("HOME").and_then(Value::as_str) {
                Some(home) => std::env::set_var("HOME", home),
                None => {
                    if let Some(home) = &saved_home {
                        std::env::set_var("HOME", home);
                    }
                }
            }
            for (key, value) in &env {
                if key != "HOME" {
                    std::env::set_var(key, value.as_str().unwrap_or_default());
                }
            }

            let entry = ServerEntry(case["entry"].as_object().cloned().unwrap_or_default());
            let actual = compute_server_hash(&entry).expect("hash computes");
            let name = case["name"].as_str().unwrap_or_default().to_string();
            assert_eq!(
                actual,
                case["expectedHash"].as_str().unwrap_or_default(),
                "configHash diverged from upstream for case {name}"
            );
            hashes.push((name, actual));
        }
    }));

    // Restore env before unwinding assertions.
    for key in [
        "RPI_MCP_FIXTURE_TOKEN",
        "RPI_MCP_FIXTURE_HOST",
        "RPI_MCP_FIXTURE_DEFINITELY_UNSET",
    ] {
        std::env::remove_var(key);
    }
    match saved_home {
        Some(home) => std::env::set_var("HOME", home),
        None => std::env::remove_var("HOME"),
    }
    for key in saved_fixture_vars {
        std::env::remove_var(key);
    }
    run.expect("hash vector comparison panicked");

    // `expectSameAs` pairs: identical identity must hash identically.
    for case in fixture["cases"].as_array().expect("cases") {
        if let Some(same_as) = case["expectSameAs"].as_str() {
            let name = case["name"].as_str().unwrap_or_default();
            let left = hashes.iter().find(|(n, _)| n == name);
            let right = hashes.iter().find(|(n, _)| n == same_as);
            assert_eq!(
                left.map(|p| &p.1),
                right.map(|p| &p.1),
                "{name} must hash like {same_as}"
            );
        }
    }
}
