//! Golden parity: tool/prompt name formatting (FR-P0-12, design §5.1).
//!
//! `fixtures/name_format_cases.json` is generated by executing the pinned
//! upstream `types.ts` @ 3d953f90 (`scripts/gen-mcp-adapter-fixtures.mjs`).

use rpi_ext_mcp_adapter::metadata::{
    format_prompt_command_name, format_tool_name, get_server_prefix, get_tool_name_candidates,
    resolve_server_from_tool_name, sanitize_prompt_name, ToolPrefix,
};
use serde_json::Value;

fn prefix(case: &Value) -> ToolPrefix {
    ToolPrefix::from_config_value(&case["prefix"]).expect("known prefix")
}

#[test]
fn name_formatting_matches_upstream() {
    let fixture: Value = serde_json::from_str(include_str!("fixtures/name_format_cases.json"))
        .expect("fixture parses");

    for case in fixture["formatToolName"].as_array().expect("cases") {
        let actual = format_tool_name(
            case["tool"].as_str().unwrap_or_default(),
            case["server"].as_str().unwrap_or_default(),
            prefix(case),
        );
        assert_eq!(
            actual,
            case["expected"].as_str().unwrap_or_default(),
            "formatToolName {case}"
        );
    }
    for case in fixture["getServerPrefix"].as_array().expect("cases") {
        let actual = get_server_prefix(case["server"].as_str().unwrap_or_default(), prefix(case));
        assert_eq!(
            actual,
            case["expected"].as_str().unwrap_or_default(),
            "getServerPrefix {case}"
        );
    }
    for case in fixture["getToolNameCandidates"].as_array().expect("cases") {
        let actual = get_tool_name_candidates(
            case["tool"].as_str().unwrap_or_default(),
            case["server"].as_str().unwrap_or_default(),
            prefix(case),
        );
        let expected: Vec<&str> = case["expected"]
            .as_array()
            .map(|a| a.iter().filter_map(Value::as_str).collect())
            .unwrap_or_default();
        assert_eq!(actual, expected, "getToolNameCandidates {case}");
    }
    for case in fixture["resolveServerFromToolName"]
        .as_array()
        .expect("cases")
    {
        let servers: Vec<&str> = case["servers"]
            .as_array()
            .map(|a| a.iter().filter_map(Value::as_str).collect())
            .unwrap_or_default();
        let actual = resolve_server_from_tool_name(
            case["tool"].as_str().unwrap_or_default(),
            servers,
            prefix(case),
        );
        assert_eq!(
            actual,
            case["expected"].as_str(),
            "resolveServerFromToolName {case}"
        );
    }
    for case in fixture["sanitizePromptName"].as_array().expect("cases") {
        let actual = sanitize_prompt_name(case["input"].as_str().unwrap_or_default());
        assert_eq!(
            actual,
            case["expected"].as_str().unwrap_or_default(),
            "sanitizePromptName {case}"
        );
    }
    for case in fixture["formatPromptCommandName"]
        .as_array()
        .expect("cases")
    {
        let actual = format_prompt_command_name(
            case["prompt"].as_str().unwrap_or_default(),
            case["server"].as_str().unwrap_or_default(),
            prefix(case),
        );
        assert_eq!(
            actual,
            case["expected"].as_str().unwrap_or_default(),
            "formatPromptCommandName {case}"
        );
    }
}
