//! Golden parity: include/excludeTools glob matching + searchKeywords
//! resolution (FR-P1-02, design §5.1).
//!
//! `fixtures/glob_cases.json` is generated by executing the pinned upstream
//! `types.ts` (`matchesToolPattern` / `isToolAllowed` /
//! `getToolNameCandidates`) + `search-ranking.ts` (`resolveSearchKeywords`)
//! @ 3d953f90 (`scripts/gen-mcp-adapter-fixtures.mjs`) — the expected
//! values ARE the upstream outputs.

use rpi_ext_mcp_adapter::metadata::{
    get_tool_name_candidates, is_tool_allowed, matches_tool_pattern, ServerEntry, ToolPrefix,
};
use rpi_ext_mcp_adapter::search::resolve_search_keywords;
use serde_json::{json, Value};

fn parse_prefix(s: &str) -> ToolPrefix {
    match s {
        "none" => ToolPrefix::None,
        "short" => ToolPrefix::Short,
        "mcp" => ToolPrefix::Mcp,
        _ => ToolPrefix::Server,
    }
}

#[test]
fn glob_matches_upstream_tool_pattern() {
    let fixture: Value =
        serde_json::from_str(include_str!("fixtures/glob_cases.json")).expect("fixture parses");

    for case in fixture["matches"].as_array().expect("match cases") {
        let tool_name = case["toolName"].as_str().unwrap_or_default();
        let server = case["server"].as_str().unwrap_or_default();
        let prefix = parse_prefix(case["prefix"].as_str().unwrap_or("server"));
        let pattern = case["pattern"].clone();

        let candidates = get_tool_name_candidates(tool_name, server, prefix);
        let actual = matches_tool_pattern(&candidates, Some(&pattern));
        let expected = case["expected"].as_bool().unwrap_or(false);
        assert_eq!(actual, expected, "matchesToolPattern diverged: {case}");
    }
}

#[test]
fn include_exclude_glob_matches_upstream_is_tool_allowed() {
    let fixture: Value =
        serde_json::from_str(include_str!("fixtures/glob_cases.json")).expect("fixture parses");

    for case in fixture["allowed"].as_array().expect("allowed cases") {
        let tool_name = case["toolName"].as_str().unwrap_or_default();
        let server = case["server"].as_str().unwrap_or_default();
        let prefix = parse_prefix(case["prefix"].as_str().unwrap_or("server"));
        let include = case.get("include");
        let exclude = case.get("exclude");

        let actual = is_tool_allowed(tool_name, server, prefix, include, exclude);
        let expected = case["expected"].as_bool().unwrap_or(false);
        assert_eq!(actual, expected, "isToolAllowed diverged: {case}");
    }
}

#[test]
fn search_keywords_resolution_matches_upstream() {
    let fixture: Value =
        serde_json::from_str(include_str!("fixtures/glob_cases.json")).expect("fixture parses");

    for case in fixture["keywords"].as_array().expect("keyword cases") {
        let tool_name = case["toolName"].as_str().unwrap_or_default();
        let server = case["server"].as_str().unwrap_or_default();
        let prefix = parse_prefix(case["prefix"].as_str().unwrap_or("server"));
        let definition = ServerEntry(case["definition"].as_object().cloned().unwrap_or_default());

        let actual = resolve_search_keywords(Some(&definition), tool_name, server, prefix);
        let expected: Vec<String> = case["expected"]
            .as_array()
            .map(|a| {
                a.iter()
                    .filter_map(Value::as_str)
                    .map(str::to_string)
                    .collect()
            })
            .unwrap_or_default();
        assert_eq!(actual, expected, "resolveSearchKeywords diverged: {case}");
    }
}

/// searchKeywords never leak into tool schemas/describe (FR-P1-02 invariant):
/// `build_tool_metadata` produces `ToolMetadata` whose description comes
/// solely from the tool itself — searchKeywords are a scoring-only sideband
/// consumed by `score_tool_match`, never embedded into metadata.
#[test]
fn search_keywords_do_not_appear_in_tool_metadata() {
    use rpi_ext_mcp_adapter::metadata::{build_tool_metadata, McpTool};
    let definition = ServerEntry(
        json!({
            "searchKeywords": {
                "demo_*": ["secret-alias", "hidden-term"]
            }
        })
        .as_object()
        .cloned()
        .unwrap_or_default(),
    );
    let tools = vec![McpTool {
        name: "search".to_string(),
        description: Some("Search records".to_string()),
        input_schema: Some(json!({"type": "object"})),
    }];
    let result = build_tool_metadata(&tools, &[], &definition, "demo", ToolPrefix::Server);
    assert_eq!(result.metadata.len(), 1);
    let desc = &result.metadata[0].description;
    assert!(!desc.contains("secret-alias"));
    assert!(!desc.contains("hidden-term"));
    // Schema is unchanged — no searchKeywords leak.
    assert_eq!(
        result.metadata[0].input_schema,
        Some(json!({"type": "object"}))
    );
}
