//! Host truncation semantics for MCP output (R7.2.10.2 / #500).
//!
//! Verbatim port of the HOST `truncateHead` semantics
//! (`crates/rpi/src/tools/truncate.rs`, itself the port of pi's
//! `truncate.ts`): the guard reuses the HOST truncation semantics and
//! formatting instead of the adapter's own byte loop
//! (`4444b49 fix(output): reuse host truncation semantics (#500)`).
//!
//! Byte-level parity is locked by `tests/golden_truncate.rs` against
//! `tests/fixtures/truncation_cases.json` — vectors generated by running
//! the HOST implementation directly (see the fixture's provenance note);
//! both directions (host→plugin, plugin→host) compare the same frozen
//! vectors.
//!
//! Only the head variant + `formatSize` are needed by the guard; the tail
//! variant stays host-owned (bash tool).

use serde::{Deserialize, Serialize};

/// Default maximum number of lines in tool output (truncate.ts:11).
pub const DEFAULT_MAX_LINES: usize = 2000;
/// Default maximum byte count in tool output — 50 KB (truncate.ts:12).
pub const DEFAULT_MAX_BYTES: usize = 50 * 1024; // 51200

/// Which limit triggered truncation. Serialised as `"lines"` / `"bytes"`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TruncatedBy {
    #[serde(rename = "lines")]
    Lines,
    #[serde(rename = "bytes")]
    Bytes,
}

/// Result of a truncation operation (host `TruncationResult`, camelCase
/// serialization — embedded in `details.outputGuard`).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TruncationResult {
    pub content: String,
    pub truncated: bool,
    pub truncated_by: Option<TruncatedBy>,
    pub total_lines: usize,
    pub total_bytes: usize,
    pub output_lines: usize,
    pub output_bytes: usize,
    pub last_line_partial: bool,
    pub first_line_exceeds_limit: bool,
    pub max_lines: usize,
    pub max_bytes: usize,
}

/// Options (host `TruncateOptions`, truncate.ts:40-45).
#[derive(Debug, Clone, Copy)]
pub struct TruncateOptions {
    pub max_lines: usize,
    pub max_bytes: usize,
}

impl Default for TruncateOptions {
    fn default() -> Self {
        Self {
            max_lines: DEFAULT_MAX_LINES,
            max_bytes: DEFAULT_MAX_BYTES,
        }
    }
}

/// `splitLinesForCounting` (truncate.ts:47-56): `split('\n')` semantics —
/// a trailing newline does not count as an extra line; empty content is
/// zero lines.
fn split_lines_for_counting(content: &str) -> Vec<&str> {
    if content.is_empty() {
        return Vec::new();
    }
    let mut lines: Vec<&str> = content.split('\n').collect();
    if content.ends_with('\n') {
        lines.pop();
    }
    lines
}

/// `formatSize` (truncate.ts:61-69): `"NB"` / `"N.NKB"` / `"N.NMB"`
/// (JS `toFixed(1)`; NOTE — the host form, not the adapter's old
/// `"N B"/"N.N KiB"` spelling).
pub fn format_size(bytes: usize) -> String {
    if bytes < 1024 {
        format!("{bytes}B")
    } else if bytes < 1024 * 1024 {
        format!("{:.1}KB", bytes as f64 / 1024.0)
    } else {
        format!("{:.1}MB", bytes as f64 / (1024.0 * 1024.0))
    }
}

/// `truncateHead` (truncate.ts:78-160): keep the first N lines/bytes.
/// Never returns partial lines; a first line larger than the byte limit
/// returns empty content with `first_line_exceeds_limit`.
pub fn truncate_head(content: &str, options: Option<TruncateOptions>) -> TruncationResult {
    let opts = options.unwrap_or_default();
    let max_lines = opts.max_lines;
    let max_bytes = opts.max_bytes;

    let total_bytes = content.len(); // UTF-8 byte length
    let lines = split_lines_for_counting(content);
    let total_lines = lines.len();

    // No truncation needed (truncate.ts:87-101)
    if total_lines <= max_lines && total_bytes <= max_bytes {
        return TruncationResult {
            content: content.to_string(),
            truncated: false,
            truncated_by: None,
            total_lines,
            total_bytes,
            output_lines: total_lines,
            output_bytes: total_bytes,
            last_line_partial: false,
            first_line_exceeds_limit: false,
            max_lines,
            max_bytes,
        };
    }

    // First-line exceeds byte limit (truncate.ts:104-119)
    let first_line_bytes = lines[0].len();
    if first_line_bytes > max_bytes {
        return TruncationResult {
            content: String::new(),
            truncated: true,
            truncated_by: Some(TruncatedBy::Bytes),
            total_lines,
            total_bytes,
            output_lines: 0,
            output_bytes: 0,
            last_line_partial: false,
            first_line_exceeds_limit: true,
            max_lines,
            max_bytes,
        };
    }

    // Collect complete lines that fit (truncate.ts:122-160)
    let mut output_bytes_count = 0usize;
    let mut truncated_by = TruncatedBy::Lines;
    let mut collected_count = 0usize;

    for (i, line) in lines.iter().enumerate().take(lines.len().min(max_lines)) {
        let line_bytes = line.len() + if i > 0 { 1 } else { 0 }; // +1 for newline

        if output_bytes_count + line_bytes > max_bytes {
            truncated_by = TruncatedBy::Bytes;
            break;
        }

        output_bytes_count += line_bytes;
        collected_count += 1;
    }

    // If we stopped because of the line limit (truncate.ts:140-142)
    if collected_count >= max_lines && output_bytes_count <= max_bytes {
        truncated_by = TruncatedBy::Lines;
    }

    let output_content: String = lines[..collected_count].join("\n");
    let final_output_bytes = output_content.len();

    TruncationResult {
        content: output_content,
        truncated: true,
        truncated_by: Some(truncated_by),
        total_lines,
        total_bytes,
        output_lines: collected_count,
        output_bytes: final_output_bytes,
        last_line_partial: false,
        first_line_exceeds_limit: false,
        max_lines,
        max_bytes,
    }
}
