//! JSON Schema -> TypeScript shape rendering for `describe` (FR-P0-05).
//!
//! Port of `ts-shape.ts` @ pi-mcp-adapter v2.24.0 (3d953f90) — the whole
//! file, including its null-on-unsupported contract (callers fall back to
//! `metadata::format_schema`). Rendering rules are a byte-level parity
//! surface; the golden fixtures in `tests/fixtures/tsshape_cases.json` are
//! generated by running the upstream module directly
//! (`scripts/gen-mcp-adapter-fixtures.mjs`).

use serde_json::{Map, Value};

/// `UNSUPPORTED_KEYWORDS` (ts-shape.ts:3).
const UNSUPPORTED_KEYWORDS: [&str; 7] = [
    "if",
    "then",
    "else",
    "allOf",
    "not",
    "patternProperties",
    "additionalProperties",
];

/// The upstream `aliases` / `usedAliases` / `aliasIndex` closure state
/// (ts-shape.ts:21-33). Aliases are assigned lazily in first-reference order
/// and keep insertion order at output time.
struct AliasAllocator {
    /// `(definitionKey, alias)` in assignment order.
    aliases: Vec<(String, String)>,
    used: Vec<String>,
    index: u32,
}

impl AliasAllocator {
    fn new() -> Self {
        Self {
            aliases: Vec::new(),
            used: Vec::new(),
            index: 0,
        }
    }

    /// `aliasFor` (ts-shape.ts:24-33).
    fn alias_for(&mut self, definition_key: &str) -> String {
        if let Some((_, alias)) = self.aliases.iter().find(|(k, _)| k == definition_key) {
            return alias.clone();
        }
        let name = definition_key
            .split_once('/')
            .map(|(_, n)| n)
            .unwrap_or(definition_key);
        let mut alias = if is_identifier(name) && !self.used.iter().any(|a| a == name) {
            name.to_string()
        } else {
            self.index += 1;
            format!("Definition{}", self.index)
        };
        while self.used.contains(&alias) {
            self.index += 1;
            alias = format!("Definition{}", self.index);
        }
        self.aliases
            .push((definition_key.to_string(), alias.clone()));
        self.used.push(alias.clone());
        alias
    }
}

/// Collected `$defs` / `definitions` entries (ts-shape.ts:10-19), keyed
/// `"{group}/{decodedName}"`.
struct Definitions<'a> {
    entries: Vec<(String, &'a Map<String, Value>)>,
}

impl<'a> Definitions<'a> {
    fn collect(root: &'a Map<String, Value>) -> Option<Self> {
        let mut entries = Vec::new();
        for key in ["$defs", "definitions"] {
            let Some(raw) = root.get(key) else { continue };
            let raw = raw.as_object()?;
            for (name, definition) in raw {
                let definition = definition.as_object()?;
                entries.push((format!("{key}/{}", decode_pointer_token(name)), definition));
            }
        }
        Some(Self { entries })
    }

    fn get(&self, key: &str) -> Option<&'a Map<String, Value>> {
        self.entries.iter().find(|(k, _)| k == key).map(|(_, v)| *v)
    }
}

/// `renderTsShape` (ts-shape.ts:6-107): render the useful JSON Schema subset
/// as TypeScript, or `None` for unsupported schemas.
pub fn render_ts_shape(input_schema: &Value) -> Option<String> {
    let root = input_schema.as_object()?;
    let definitions = Definitions::collect(root)?;
    let mut aliases = AliasAllocator::new();

    let root_rendered = render(input_schema, &definitions, &mut aliases)?;

    // Upstream iterates the live `aliases` Map, so definitions whose bodies
    // reference not-yet-aliased definitions are appended during iteration and
    // rendered too — index loop replicates that.
    let mut definitions_text: Vec<String> = Vec::new();
    let mut i = 0;
    while i < aliases.aliases.len() {
        let (key, alias) = aliases.aliases[i].clone();
        let definition = definitions.get(&key)?;
        let rendered = render(
            &Value::Object(definition.clone()),
            &definitions,
            &mut aliases,
        )?;
        definitions_text.push(format!("type {alias} = {rendered};"));
        i += 1;
    }
    if definitions_text.is_empty() {
        Some(root_rendered)
    } else {
        Some(format!(
            "{}\n\n{}",
            definitions_text.join("\n"),
            root_rendered
        ))
    }
}

/// The `render` closure (ts-shape.ts:35-90).
fn render(
    schema: &Value,
    definitions: &Definitions,
    aliases: &mut AliasAllocator,
) -> Option<String> {
    let map = schema.as_object()?;
    if has_unsupported_keyword(map) {
        return None;
    }

    if map.contains_key("$ref") {
        let reference = map.get("$ref").and_then(Value::as_str)?;
        let (group, name) = parse_local_ref(reference)?;
        let definition_key = format!("{group}/{}", decode_pointer_token(name));
        definitions.get(&definition_key)?;
        return Some(aliases.alias_for(&definition_key));
    }

    if let Some(Value::Array(values)) = map.get("enum") {
        let mut rendered = Vec::with_capacity(values.len());
        for value in values {
            rendered.push(render_literal(value)?);
        }
        return Some(rendered.join(" | "));
    }
    if map.contains_key("const") {
        return render_literal(map.get("const").unwrap_or(&Value::Null));
    }

    let variants = match (map.get("anyOf"), map.get("oneOf")) {
        (Some(Value::Array(v)), _) => Some(v),
        (_, Some(Value::Array(v))) => Some(v),
        _ => None,
    };
    if let Some(variants) = variants {
        if variants.is_empty() {
            return None;
        }
        let mut rendered = Vec::with_capacity(variants.len());
        for variant in variants {
            rendered.push(render(variant, definitions, aliases)?);
        }
        return Some(rendered.join(" | "));
    }

    if map.get("type").and_then(Value::as_str) == Some("object") || map.contains_key("properties") {
        let Some(properties) = map.get("properties") else {
            return Some("{}".to_string());
        };
        let properties = properties.as_object()?;
        let required: Vec<&str> = match map.get("required") {
            Some(Value::Array(list)) => list.iter().filter_map(Value::as_str).collect(),
            _ => Vec::new(),
        };
        let mut rendered_properties: Vec<String> = Vec::new();
        for (name, property) in properties {
            let rendered = render(property, definitions, aliases)?;
            let optional = if required.contains(&name.as_str()) {
                ""
            } else {
                "?"
            };
            rendered_properties.push(format!(
                "{}{optional}: {rendered};",
                format_property_name(name)
            ));
        }
        return if rendered_properties.is_empty() {
            Some("{}".to_string())
        } else {
            Some(format!("{{ {} }}", rendered_properties.join(" ")))
        };
    }

    if map.get("type").and_then(Value::as_str) == Some("array") {
        let Some(items) = map.get("items") else {
            return Some("unknown[]".to_string());
        };
        let item = render(items, definitions, aliases)?;
        return Some(if needs_parentheses(&item) {
            format!("({item})[]")
        } else {
            format!("{item}[]")
        });
    }

    if let Some(Value::Array(types)) = map.get("type") {
        let mut rendered = Vec::with_capacity(types.len());
        for t in types {
            rendered.push(render_type(t)?);
        }
        return Some(rendered.join(" | "));
    }
    if let Some(t) = map.get("type").and_then(Value::as_str) {
        return render_type(&Value::String(t.to_string()));
    }
    Some("unknown".to_string())
}

/// `hasUnsupportedKeyword` (ts-shape.ts:113-119): `additionalProperties:
/// false` is a closed-object constraint, not an unsupported shape.
fn has_unsupported_keyword(schema: &Map<String, Value>) -> bool {
    UNSUPPORTED_KEYWORDS.iter().any(|keyword| {
        if !schema.contains_key(*keyword) {
            return false;
        }
        *keyword != "additionalProperties" || schema.get(*keyword) != Some(&Value::Bool(false))
    })
}

/// `decodePointerToken` (ts-shape.ts:121-123).
fn decode_pointer_token(token: &str) -> String {
    token.replace("~1", "/").replace("~0", "~")
}

/// The `#/($defs|definitions)/<name>` regex (ts-shape.ts:40).
fn parse_local_ref(reference: &str) -> Option<(&str, &str)> {
    let rest = reference.strip_prefix("#/")?;
    let (group, name) = rest.split_once('/')?;
    if group != "$defs" && group != "definitions" {
        return None;
    }
    // `([^/]+)`: non-empty, no further separators.
    if name.is_empty() || name.contains('/') {
        return None;
    }
    Some((group, name))
}

/// `renderType` (ts-shape.ts:125-136).
fn render_type(value: &Value) -> Option<String> {
    match value.as_str()? {
        "string" => Some("string".to_string()),
        "number" | "integer" => Some("number".to_string()),
        "boolean" => Some("boolean".to_string()),
        "null" => Some("null".to_string()),
        "object" => Some("{}".to_string()),
        "array" => Some("unknown[]".to_string()),
        _ => None,
    }
}

/// `renderLiteral` (ts-shape.ts:138-141).
fn render_literal(value: &Value) -> Option<String> {
    match value {
        Value::Null | Value::String(_) | Value::Bool(_) => {
            Some(crate::utils::js_json_stringify(value))
        }
        Value::Number(n) => n
            .as_f64()
            .filter(|f| f.is_finite())
            .map(|_| crate::utils::js_json_stringify(value)),
        _ => None,
    }
}

/// JS identifier check for `/^[A-Za-z_$][\w$]*$/` (ts-shape.ts:28, 144).
fn is_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first.is_ascii_alphabetic() || first == '_' || first == '$') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
}

/// `formatPropertyName` (ts-shape.ts:143-145).
fn format_property_name(name: &str) -> String {
    if is_identifier(name) {
        name.to_string()
    } else {
        crate::utils::js_json_stringify(&Value::String(name.to_string()))
    }
}

/// `needsParentheses` (ts-shape.ts:147-149).
fn needs_parentheses(rendered: &str) -> bool {
    rendered.contains(" | ")
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    // Intent ports of `__tests__/ts-shape.test.ts` @ 3d953f90. The byte-level
    // golden set (generated from the upstream module) lives in
    // `tests/golden_tsshape.rs`.

    #[test]
    fn renders_required_and_optional_object_properties() {
        let schema = json!({
            "type": "object",
            "properties": { "query": { "type": "string" }, "limit": { "type": "integer" } },
            "required": ["query"],
        });
        assert_eq!(
            render_ts_shape(&schema).as_deref(),
            Some("{ query: string; limit?: number; }")
        );
    }

    #[test]
    fn renders_enum_unions() {
        let schema = json!({ "enum": ["fast", "safe", null] });
        assert_eq!(
            render_ts_shape(&schema).as_deref(),
            Some("\"fast\" | \"safe\" | null")
        );
    }

    #[test]
    fn renders_nested_objects_and_arrays() {
        let schema = json!({
            "type": "object",
            "properties": {
                "config": {
                    "type": "object",
                    "properties": { "tags": { "type": "array", "items": { "type": "string" } } },
                    "required": ["tags"],
                },
            },
            "required": ["config"],
        });
        assert_eq!(
            render_ts_shape(&schema).as_deref(),
            Some("{ config: { tags: string[]; }; }")
        );
    }

    #[test]
    fn hoists_local_references_as_named_definitions() {
        let schema = json!({
            "type": "object",
            "properties": { "address": { "$ref": "#/$defs/Address" } },
            "required": ["address"],
            "$defs": {
                "Address": {
                    "type": "object",
                    "properties": { "city": { "type": "string" } },
                    "required": ["city"],
                },
            },
        });
        assert_eq!(
            render_ts_shape(&schema).as_deref(),
            Some("type Address = { city: string; };\n\n{ address: Address; }")
        );
    }

    #[test]
    fn ignores_unsupported_unreferenced_definitions() {
        let schema = json!({
            "type": "object",
            "properties": { "query": { "type": "string" } },
            "required": ["query"],
            "$defs": { "Unused": { "if": { "type": "string" }, "then": { "type": "number" } } },
        });
        assert_eq!(
            render_ts_shape(&schema).as_deref(),
            Some("{ query: string; }")
        );
    }

    #[test]
    fn renders_closed_objects_with_referenced_union_variants() {
        let schema = json!({
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "blocks": { "type": "array", "items": { "$ref": "#/$defs/block" } },
            },
            "required": ["blocks"],
            "$defs": {
                "text": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": { "type": { "const": "text" }, "text": { "type": "string" } },
                    "required": ["type", "text"],
                },
                "qr": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": { "type": { "const": "qr" }, "data": { "type": "string" } },
                    "required": ["type", "data"],
                },
                "block": { "oneOf": [{ "$ref": "#/$defs/text" }, { "$ref": "#/$defs/qr" }] },
            },
        });
        assert_eq!(
            render_ts_shape(&schema).as_deref(),
            Some(
                [
                    "type block = text | qr;",
                    "type text = { type: \"text\"; text: string; };",
                    "type qr = { type: \"qr\"; data: string; };",
                    "",
                    "{ blocks: block[]; }",
                ]
                .join("\n")
                .as_str()
            )
        );
    }

    #[test]
    fn returns_none_for_exotic_schemas() {
        assert_eq!(
            render_ts_shape(&json!({ "if": { "type": "string" }, "then": { "type": "number" } })),
            None
        );
        assert_eq!(
            render_ts_shape(&json!({ "$ref": "https://example.com/schema" })),
            None
        );
        assert_eq!(render_ts_shape(&json!(42)), None);
    }
}
