#!/usr/bin/env python3
"""Generate examples/models.json — a common-provider template for `rpi`.

The template is derived from the vendored built-in catalog
(crates/rpi-ai/src/providers/data/*.json, read-only upstream data) so the
model lists always match the shipped catalog. Only providers reachable
through models.json are included (the models.json `api` field can only select
the four stream kinds registered in `ModelRuntime::api_streams`:
openai-completions / openai-responses / anthropic-messages /
azure-openai-responses; google-generative-ai, google-vertex,
bedrock-converse-stream and mistral-conversations are NOT configurable via
models.json in this port).

Env var names are taken from the provider factories in
crates/rpi-ai/src/providers/ (the same names the native factories read).
The apiKey value in models.json is an *environment variable name*, not the
key itself (model-runtime.rs:11).

Usage:
    python3 scripts/generate-common-models-json.py > examples/models.json
"""

import json
from pathlib import Path

DATA = Path(__file__).resolve().parent.parent / "crates" / "rpi-ai" / "src" / "providers" / "data"

# (data file, provider id, display name, env var, chosen api when multi-api)
PROVIDERS = [
    ("anthropic.json", "anthropic", "Anthropic", "ANTHROPIC_API_KEY", None),
    ("openai.json", "openai", "OpenAI", "OPENAI_API_KEY", None),
    ("deepseek.json", "deepseek", "DeepSeek", "DEEPSEEK_API_KEY", None),
    # xai.json carries both openai-completions (grok-4.3, grok-build) and
    # openai-responses (grok-4.5) groups; models.json composes a single
    # stream kind, so pick the responses group (flagship grok-4.5).
    ("xai.json", "xai", "xAI", "XAI_API_KEY", "openai-responses"),
    ("openrouter.json", "openrouter", "OpenRouter", "OPENROUTER_API_KEY", None),
    ("groq.json", "groq", "Groq", "GROQ_API_KEY", None),
    ("cerebras.json", "cerebras", "Cerebras", "CEREBRAS_API_KEY", None),
    ("moonshotai.json", "moonshotai", "Moonshot AI", "MOONSHOT_API_KEY", None),
    ("moonshotai-cn.json", "moonshotai-cn", "Moonshot AI CN", "MOONSHOT_API_KEY", None),
    ("minimax-cn.json", "minimax-cn", "MiniMax CN", "MINIMAX_CN_API_KEY", None),
    ("qwen-token-plan-cn.json", "qwen-token-plan-cn", "Qwen Token Plan CN", "QWEN_TOKEN_PLAN_CN_API_KEY", None),
    ("zai.json", "zai", "Z.AI", "ZAI_API_KEY", None),
]

# Model fields accepted by the ModelsJsonModel schema (models_json.rs); the
# data files also carry `api`/`provider`/`baseUrl` per model, which are
# dropped (provider-level api/baseUrl is authoritative, and the composed
# provider dispatches through a single stream kind).
MODEL_FIELDS = [
    "id",
    "name",
    "reasoning",
    "thinkingLevelMap",
    "input",
    "cost",
    "contextWindow",
    "maxTokens",
    "compat",
]


def main() -> None:
    providers = {}
    for data_file, provider_id, name, env_var, chosen_api in PROVIDERS:
        raw = json.loads((DATA / data_file).read_text())
        if chosen_api is not None:
            groups = {k: v for k, v in raw.items() if k == chosen_api}
        else:
            groups = raw
        assert len(groups) == 1, f"{data_file}: expected one api group, got {list(groups)}"
        api, models = next(iter(groups.items()))
        providers[provider_id] = {
            "name": name,
            "baseUrl": next(iter(models.values()))["baseUrl"],
            "api": api,
            "apiKey": env_var,
            "models": [
                {k: m[k] for k in MODEL_FIELDS if k in m}
                for m in sorted(models.values(), key=lambda m: m["id"])
            ],
        }

    print("// Common provider template for rpi — install to ~/.rpi/agent/models.json")
    print("// (or {RPI_CODING_AGENT_DIR}/models.json). apiKey is an ENV VAR NAME,")
    print("// not the key itself. Generated by scripts/generate-common-models-json.py")
    print("// from the vendored built-in catalog; model lists match the shipped data.")
    print(json.dumps({"providers": providers}, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
