//! Syntax highlighting — the Rust slice of `highlightCode` /
//! `getLanguageFromPath` / `supportsLanguage`
//! (`packages/coding-agent/src/modes/interactive/theme/theme.ts:1160-1250` and
//! `packages/coding-agent/src/utils/syntax-highlight.ts`) @ pi 0.82.1 (2efa728).
//!
//! Upstream highlights with highlight.js 10.7.3 through a self-written
//! HTML→ANSI renderer; rpi uses syntect (Sublime Text grammars) per
//! ADR-0008 / D-051, so the ANSI token boundaries differ from upstream while
//! the scope→color mapping is anchored to the same `buildCliHighlightTheme`
//! theme keys (theme.ts:1118-1146) — same color family for the same token
//! kind.
//!
//! Intentional differences:
//! - The embedded syntax set is bat's curated set (generated by `build.rs`
//!   from `syntect-assets`), not syntect's built-in defaults — the latter
//!   lack TypeScript/TOML/Dockerfile/… as of syntect 5.3. Six grammars whose
//!   regexes the pure-Rust fancy-regex backend cannot compile are excluded
//!   (see [`FANCY_INCOMPATIBLE`]); of the 43 languages reachable through
//!   [`get_language_from_path`], only `powershell` is affected and falls back
//!   to the plain `mdCodeBlock` color like any unsupported language.
//! - `supportsLanguage` (hljs `getLanguage` name/alias lookup) becomes
//!   "resolvable in the embedded syntect syntax set by name or alias,
//!   case-insensitive".
//! - Scope matching mirrors the upstream formatter resolution order
//!   (exact → dot prefix → dash prefix, innermost span first,
//!   syntax-highlight.ts:33-70) via an ordered prefix table — see
//!   [`SCOPE_STYLES`].

use std::sync::OnceLock;

use syntect::parsing::{ParseState, ScopeStack, SyntaxReference, SyntaxSet};
use syntect::util::LinesWithEndings;

use crate::core::themes::Theme;

// ===========================================================================
// Embedded syntax set (generated by build.rs)
// ===========================================================================

/// zlib-compressed bincode dump of the syntax set, written by `build.rs`
/// into `OUT_DIR` (bat's curated set, fancy-regex verified).
static SYNTAX_SET: OnceLock<Result<SyntaxSet, String>> = OnceLock::new();

fn syntax_set() -> Option<&'static SyntaxSet> {
    SYNTAX_SET
        .get_or_init(|| {
            let dump: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/syntaxes.bin"));
            syntect::dumps::from_reader(dump).map_err(|e| format!("load embedded syntax dump: {e}"))
        })
        .as_ref()
        .ok()
}

/// Syntaxes excluded from highlighting because fancy-regex cannot compile
/// their regexes (syntect panics on such a regex at parse time; the build
/// script verifies this list exhaustively). Mirror of the same list in
/// `build.rs` — keep the two in sync.
const FANCY_INCOMPATIBLE: &[&str] = &[
    "ARM Assembly",
    "JavaScript (Babel)",
    "PowerShell",
    "Regular Expressions (Elixir)",
    "Salt State (SLS)",
    "VimHelp",
];

// ===========================================================================
// Language lookup (`getLanguageFromPath`, theme.ts:1184-1250)
// ===========================================================================

/// Extension → language table, ported verbatim (all 58 entries) from
/// `getLanguageFromPath` (theme.ts:1188-1247). Values are the hljs-style
/// canonical names returned to callers.
const EXT_TO_LANG: &[(&str, &str)] = &[
    ("ts", "typescript"),
    ("tsx", "typescript"),
    ("js", "javascript"),
    ("jsx", "javascript"),
    ("mjs", "javascript"),
    ("cjs", "javascript"),
    ("py", "python"),
    ("rb", "ruby"),
    ("rs", "rust"),
    ("go", "go"),
    ("java", "java"),
    ("kt", "kotlin"),
    ("swift", "swift"),
    ("c", "c"),
    ("h", "c"),
    ("cpp", "cpp"),
    ("cc", "cpp"),
    ("cxx", "cpp"),
    ("hpp", "cpp"),
    ("cs", "csharp"),
    ("php", "php"),
    ("sh", "bash"),
    ("bash", "bash"),
    ("zsh", "bash"),
    ("fish", "fish"),
    ("ps1", "powershell"),
    ("sql", "sql"),
    ("html", "html"),
    ("htm", "html"),
    ("css", "css"),
    ("scss", "scss"),
    ("sass", "sass"),
    ("less", "less"),
    ("json", "json"),
    ("yaml", "yaml"),
    ("yml", "yaml"),
    ("toml", "toml"),
    ("xml", "xml"),
    ("md", "markdown"),
    ("markdown", "markdown"),
    ("dockerfile", "dockerfile"),
    ("makefile", "makefile"),
    ("cmake", "cmake"),
    ("lua", "lua"),
    ("perl", "perl"),
    ("r", "r"),
    ("scala", "scala"),
    ("clj", "clojure"),
    ("ex", "elixir"),
    ("exs", "elixir"),
    ("erl", "erlang"),
    ("hs", "haskell"),
    ("ml", "ocaml"),
    ("vim", "vim"),
    ("graphql", "graphql"),
    ("proto", "protobuf"),
    ("tf", "hcl"),
    ("hcl", "hcl"),
];

/// `getLanguageFromPath` (theme.ts:1184-1186): the extension is the last dot
/// segment of the path, lowercased (the whole path for dot-less names, which
/// is how upstream resolves `Makefile`/`Dockerfile` file names).
pub fn get_language_from_path(path: &str) -> Option<&'static str> {
    let ext = path.rsplit('.').next().unwrap_or("").to_ascii_lowercase();
    EXT_TO_LANG
        .iter()
        .find(|(e, _)| *e == ext)
        .map(|(_, lang)| *lang)
}

// ===========================================================================
// Language-name resolution (`supportsLanguage`, syntax-highlight.ts:144-146)
// ===========================================================================

/// Canonical language names from the extension table whose syntect syntax
/// name differs from the hljs-style name (`get_language_from_path` returns
/// these names; resolution must find the syntax anyway).
const CANONICAL_NAME_REDIRECTS: &[(&str, &str)] = &[
    ("cpp", "C++"),
    ("csharp", "C#"),
    ("bash", "Bourne Again Shell (bash)"),
    ("vim", "VimL"),
    ("protobuf", "Protocol Buffer"),
    ("hcl", "Terraform"),
];

/// The complete alias set hljs 10.7.3 ships (read from
/// `node_modules/highlight.js/lib/languages/*.js` `aliases` arrays).
///
/// hljs resolves every alias to its language's grammar; the syntect targets
/// below are that grammar's counterpart in the embedded bat set. Judgment
/// calls (D-051 covers tokenization, not resolution):
/// - `jsx` maps to plain JavaScript like hljs (syntect's
///   `JavaScript (Babel)` is fancy-incompatible anyway); `tsx` maps to the
///   bat set's TSX grammar `TypeScriptReact`; `jsp` to
///   `Java Server Page (JSP)`;
/// - xml's `html`/`xhtml` aliases map to syntect `HTML` (the display
///   equivalent of hljs's xml grammar applied to HTML), the remaining xml
///   aliases to `XML`;
/// - hljs languages with no counterpart in the bat set (haxe, smalltalk,
///   brainfuck, …) stay unsupported, as do `ps`/`ps1`/`arm` whose bat
///   syntaxes are fancy-incompatible, and `toml` (hljs maps it to `ini`;
///   rpi resolves the richer `TOML` syntax directly by name).
const LANGUAGE_ALIASES: &[(&str, &str)] = &[
    ("py", "Python"),
    ("gyp", "Python"),
    ("ipython", "Python"),
    ("md", "Markdown"),
    ("mkdown", "Markdown"),
    ("mkd", "Markdown"),
    ("golang", "Go"),
    ("docker", "Dockerfile"),
    ("cmake.in", "CMake"),
    ("mk", "Makefile"),
    ("mak", "Makefile"),
    ("make", "Makefile"),
    ("ts", "TypeScript"),
    ("tsx", "TypeScriptReact"),
    ("js", "JavaScript"),
    ("jsx", "JavaScript"),
    ("mjs", "JavaScript"),
    ("cjs", "JavaScript"),
    ("sh", "Bourne Again Shell (bash)"),
    ("zsh", "Bourne Again Shell (bash)"),
    ("rs", "Rust"),
    ("h", "C"),
    ("cc", "C++"),
    ("c++", "C++"),
    ("h++", "C++"),
    ("hpp", "C++"),
    ("hh", "C++"),
    ("hxx", "C++"),
    ("cxx", "C++"),
    ("cs", "C#"),
    ("c#", "C#"),
    ("php3", "PHP"),
    ("php4", "PHP"),
    ("php5", "PHP"),
    ("php6", "PHP"),
    ("php7", "PHP"),
    ("php8", "PHP"),
    ("pl", "Perl"),
    ("pm", "Perl"),
    ("erl", "Erlang"),
    ("hs", "Haskell"),
    ("ml", "OCaml"),
    ("kt", "Kotlin"),
    ("kts", "Kotlin"),
    ("jsp", "Java Server Page (JSP)"),
    ("rb", "Ruby"),
    ("gemspec", "Ruby"),
    ("podspec", "Ruby"),
    ("thor", "Ruby"),
    ("irb", "Ruby"),
    ("yml", "YAML"),
    ("html", "HTML"),
    ("xhtml", "HTML"),
    ("rss", "XML"),
    ("atom", "XML"),
    ("xjb", "XML"),
    ("xsd", "XML"),
    ("xsl", "XML"),
    ("plist", "XML"),
    ("wsf", "XML"),
    ("svg", "XML"),
    // Remaining hljs 10.7.3 aliases whose language has a counterpart in the
    // embedded bat syntax set (languages with no counterpart — haxe,
    // smalltalk, verilog-adjacent asm, … — stay unsupported, as do
    // `ps`/`ps1`/`arm` whose bat syntaxes are fancy-incompatible).
    ("as", "ActionScript"),
    ("apacheconf", "Apache Conf"),
    ("adoc", "AsciiDoc (Asciidoctor)"),
    ("osascript", "AppleScript"),
    ("bat", "Batch File"),
    ("cmd", "Batch File"),
    ("clj", "Clojure"),
    ("coffee", "CoffeeScript"),
    ("cson", "CoffeeScript"),
    ("iced", "CoffeeScript"),
    ("cr", "Crystal"),
    ("patch", "Diff"),
    ("f90", "Fortran (Modern)"),
    ("f95", "Fortran (Modern)"),
    ("fs", "F#"),
    ("tex", "LaTeX"),
    ("mm", "Objective-C"),
    ("objc", "Objective-C"),
    ("obj-c", "Objective-C"),
    ("obj-c++", "Objective-C++"),
    ("objective-c++", "Objective-C++"),
    ("pas", "Pascal"),
    ("pascal", "Pascal"),
    ("dpr", "Pascal"),
    ("dfm", "Pascal"),
    ("freepascal", "Pascal"),
    ("lazarus", "Pascal"),
    ("lpr", "Pascal"),
    ("lfm", "Pascal"),
    ("nixos", "Nix"),
    ("nginxconf", "nginx"),
    ("v", "Verilog"),
    ("sv", "SystemVerilog"),
    ("svh", "SystemVerilog"),
    ("https", "HTTP Request and Response"),
    ("styl", "Stylus"),
    ("tk", "Tcl"),
    ("pp", "Puppet"),
    ("qt", "QML"),
    ("jinja", "Jinja2"),
    ("shell", "Shell-Unix-Generic"),
    ("console", "Shell-Unix-Generic"),
    ("mysql", "SQL"),
    ("oracle", "SQL"),
];

/// Resolve a language name to a syntax reference: exact name, then
/// case-insensitive name scan, then the redirect/alias tables (hljs
/// `getLanguage` semantics, syntax-highlight.ts:144-146). Excluded syntaxes
/// never resolve.
fn find_syntax(name: &str) -> Option<&'static SyntaxReference> {
    let set = syntax_set()?;
    let target = CANONICAL_NAME_REDIRECTS
        .iter()
        .chain(LANGUAGE_ALIASES)
        .find(|(alias, _)| alias.eq_ignore_ascii_case(name))
        .map(|(_, syntax_name)| *syntax_name)
        .unwrap_or(name);
    let syntax = set.find_syntax_by_name(target).or_else(|| {
        set.syntaxes()
            .iter()
            .find(|s| s.name.eq_ignore_ascii_case(target))
    })?;
    if FANCY_INCOMPATIBLE.contains(&syntax.name.as_str()) {
        return None;
    }
    Some(syntax)
}

/// `supportsLanguage` (theme.ts:1161-1162): whether a language name can be
/// highlighted. hljs resolves names and aliases case-insensitively; syntect
/// syntax names are title-case, so the check is case-insensitive.
pub fn supports_language(name: &str) -> bool {
    find_syntax(name).is_some()
}

// ===========================================================================
// Scope → theme mapping (`buildCliHighlightTheme`, theme.ts:1118-1146)
// ===========================================================================

/// A style operation on a text run — either a theme foreground color or one
/// of the raw chalk-style helpers (bold/italic/underline, theme.ts:1140-1142).
#[derive(Clone, Copy, PartialEq, Eq)]
enum Style {
    Fg(&'static str),
    Bold,
    Italic,
    Underline,
}

/// Ordered scope-prefix table mirroring `buildCliHighlightTheme`'s hljs class
/// families. Matching is prefix-based (`scope == prefix` or
/// `scope.starts_with(prefix + ".")`), which corresponds to upstream's
/// `exact → dot prefix → dash prefix` resolution (syntax-highlight.ts:33-56;
/// TextMate scopes contain no dashes, so the dash rule never fires here), and
/// the table order encodes specificity — `keyword.operator` wins over
/// `keyword`, and `meta` (the whole-construct wrapper) is the last fallback
/// tier, matching upstream's `meta → muted` mapping. Unmatched scopes stay
/// uncolored. hljs classes upstream also maps (built_in/class/type/title/tag/
/// name/attr/params/doctag/literal/emphasis/strong/link/addition/deletion)
/// are covered by these syntect scope families: built_in→support.*, class/
/// title→entity.name.*, type→storage.type, tag→meta.tag (muted wrapper),
/// name→entity.name.*, attr/params→variable.*, doctag→comment.*, literal→
/// constant.language, emphasis/strong/link→markup.italic/bold/underline.link,
/// addition/deletion→markup.inserted/deleted.
const SCOPE_STYLES: &[(&str, Style)] = &[
    ("keyword.operator", Style::Fg("syntaxOperator")),
    ("keyword", Style::Fg("syntaxKeyword")),
    ("comment", Style::Fg("syntaxComment")),
    ("string", Style::Fg("syntaxString")),
    ("constant.numeric", Style::Fg("syntaxNumber")),
    ("constant.language", Style::Fg("syntaxNumber")),
    ("entity.name.function", Style::Fg("syntaxFunction")),
    // Class declaration names: upstream hljs emits the `title` class for them
    // (`title` → syntaxFunction, theme.ts:1130).
    ("entity.name.class", Style::Fg("syntaxFunction")),
    ("support.function", Style::Fg("syntaxFunction")),
    ("entity.name.type", Style::Fg("syntaxType")),
    ("storage.type", Style::Fg("syntaxType")),
    ("support.type", Style::Fg("syntaxType")),
    ("variable", Style::Fg("syntaxVariable")),
    ("support.constant", Style::Fg("syntaxVariable")),
    ("punctuation", Style::Fg("syntaxPunctuation")),
    ("markup.underline.link", Style::Underline),
    ("markup.bold", Style::Bold),
    ("markup.italic", Style::Italic),
    ("markup.inserted", Style::Fg("toolDiffAdded")),
    ("markup.deleted", Style::Fg("toolDiffRemoved")),
    // NOTE: upstream maps the hljs `meta` class to `muted` (theme.ts:1128),
    // but syntect `meta.*` scopes wrap ordinary code everywhere (function and
    // block bodies), so a `meta → muted` fallback would render plain text
    // grey. Unmatched scopes stay uncolored, matching upstream's "no class →
    // no styling" look (ADR-0008 visual-intent alignment).
];

fn style_for_scope(scope: &str) -> Option<Style> {
    SCOPE_STYLES.iter().find_map(|(prefix, style)| {
        let matched = scope == *prefix
            || scope
                .strip_prefix(prefix)
                .is_some_and(|rest| rest.starts_with('.'));
        matched.then_some(*style)
    })
}

/// Apply the innermost matching style, walking the stack from the top —
/// upstream `getActiveFormatter` iterates the hljs span classes innermost
/// first (syntax-highlight.ts:58-70).
fn render_range(text: &str, stack: &ScopeStack, theme: &Theme) -> String {
    if text.is_empty() {
        return String::new();
    }
    let Some(style) = stack
        .as_slice()
        .iter()
        .rev()
        .find_map(|scope| style_for_scope(&scope.to_string()))
    else {
        return text.to_string();
    };
    match style {
        Style::Fg(color) => theme.fg(color, text),
        Style::Bold => Theme::bold(text),
        Style::Italic => Theme::italic(text),
        Style::Underline => Theme::underline(text),
    }
}

// ===========================================================================
// highlightCode (theme.ts:1160-1179)
// ===========================================================================

/// Highlight `code` in the given language, returning one styled line per
/// line of input (the same shape as upstream `highlight(code, opts).split(
/// "\n")`).
///
/// Fallbacks, mirroring theme.ts:1160-1179: an invalid/unknown language (or
/// `None`) colors each line with `mdCodeBlock` (upstream deliberately skips
/// hljs auto-detection, which misidentifies prose); any syntect error — and
/// any panic from a grammar the fancy-regex backend cannot compile, which the
/// embedded set is verified against at build time — returns the plain
/// uncolored lines (upstream's `try/catch`, theme.ts:1174-1178).
pub fn highlight_code(code: &str, lang: Option<&str>, theme: &Theme) -> Vec<String> {
    // `validLang = lang && supportsLanguage(lang) ? lang : undefined`
    // (theme.ts:1161-1162).
    let Some(lang) = lang.filter(|l| supports_language(l)) else {
        return code
            .split('\n')
            .map(|line| theme.fg("mdCodeBlock", line))
            .collect();
    };
    let Some(syntax) = find_syntax(lang) else {
        return code
            .split('\n')
            .map(|line| theme.fg("mdCodeBlock", line))
            .collect();
    };
    if code.is_empty() {
        // Upstream: `"".split("\n")` yields one empty line.
        return vec![String::new()];
    }
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        highlight_lines(code, syntax, theme)
    })) {
        Ok(Ok(lines)) => lines,
        Ok(Err(_)) | Err(_) => code.split('\n').map(str::to_string).collect(),
    }
}

fn highlight_lines(
    code: &str,
    syntax: &'static SyntaxReference,
    theme: &Theme,
) -> Result<Vec<String>, String> {
    let Some(set) = syntax_set() else {
        return Err("embedded syntax set unavailable".to_string());
    };
    let mut parse_state = ParseState::new(syntax);
    // Scope stack is advanced by the ops `parse_line` returns, exactly like
    // syntect's `HighlightState` does (highlighting/highlighter.rs).
    let mut stack = ScopeStack::new();
    let mut lines: Vec<String> = Vec::new();
    for chunk in LinesWithEndings::from(code) {
        // Parse in newlines mode (grammars are line-aware); render without the
        // trailing newline — the returned lines are upstream's
        // `highlight(code, opts).split("\n")` elements (theme.ts:1175), which
        // the markdown renderer pushes as whole lines.
        let content = chunk.strip_suffix('\n').unwrap_or(chunk);
        let ops = parse_state
            .parse_line(chunk, set)
            .map_err(|e| e.to_string())?;
        let mut rendered = String::with_capacity(content.len() * 2);
        let mut pos = 0usize;
        for (end, op) in ops {
            // Ops may reference the newline position past the content.
            let end = end.min(content.len());
            let snapshot = stack.clone();
            rendered.push_str(&render_range(&content[pos..end], &snapshot, theme));
            stack.apply(&op).map_err(|e| e.to_string())?;
            pos = end;
        }
        if pos < content.len() {
            rendered.push_str(&render_range(&content[pos..], &stack, theme));
        }
        lines.push(rendered);
    }
    if code.ends_with('\n') {
        // Upstream `split("\n")` keeps the trailing empty element.
        lines.push(String::new());
    }
    Ok(lines)
}

// ===========================================================================
// Tests
// ===========================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::themes::load_theme;

    fn theme() -> Theme {
        load_theme("dark", None).expect("builtin dark theme must load")
    }

    /// Strip SGR sequences — test-only approximation of terminal display.
    fn strip_ansi(s: &str) -> String {
        let mut out = String::with_capacity(s.len());
        let mut rest = s;
        while let Some(idx) = rest.find('\x1b') {
            out.push_str(&rest[..idx]);
            let tail = &rest[idx..];
            if tail.as_bytes().get(1) != Some(&b'[') {
                out.push_str(tail);
                return out;
            }
            match tail.find('m') {
                Some(end) => rest = &tail[end + 1..],
                None => {
                    out.push_str(tail);
                    return out;
                }
            }
        }
        out.push_str(rest);
        out
    }

    // --- getLanguageFromPath: all 58 extension entries ----------------------

    #[test]
    fn extension_table_maps_every_entry() {
        for (ext, lang) in EXT_TO_LANG {
            let got = get_language_from_path(&format!("file.{ext}"));
            assert_eq!(got, Some(*lang), "extension .{ext} should map to {lang}");
        }
    }

    #[test]
    fn extension_lookup_mirrors_upstream_quirks() {
        // Whole dot-less path is the "extension" (upstream split(".").pop()).
        assert_eq!(get_language_from_path("Makefile"), Some("makefile"));
        assert_eq!(get_language_from_path("Dockerfile"), Some("dockerfile"));
        // Case-insensitive extension (toLowerCase).
        assert_eq!(get_language_from_path("src/App.TS"), Some("typescript"));
        // Directories and multi-dot names.
        assert_eq!(get_language_from_path("a/b/c.rs"), Some("rust"));
        assert_eq!(get_language_from_path("archive.tar.gz"), None);
        assert_eq!(get_language_from_path("noext"), None);
        assert_eq!(get_language_from_path(""), None);
        assert_eq!(get_language_from_path("file."), None);
    }

    #[test]
    fn every_mapped_language_is_highlightable_except_powershell() {
        let mut langs: Vec<&str> = EXT_TO_LANG.iter().map(|(_, l)| *l).collect();
        langs.sort_unstable();
        langs.dedup();
        assert_eq!(langs.len(), 43);
        for lang in &langs {
            if *lang == "powershell" {
                // PowerShell's grammar uses `\g<...>` subroutine calls, which
                // fancy-regex cannot compile (see FANCY_INCOMPATIBLE); it
                // falls back like any unsupported language.
                assert!(!supports_language(lang), "powershell must be excluded");
                continue;
            }
            assert!(supports_language(lang), "{lang} must be highlightable");
        }
    }

    // --- supportsLanguage ----------------------------------------------------

    #[test]
    fn supports_language_positive_and_negative() {
        for lang in [
            "rust",
            "python",
            "typescript",
            "json",
            "bash",
            "csharp",
            "protobuf",
        ] {
            assert!(supports_language(lang), "{lang} must be supported");
        }
        // Case-insensitive, like hljs getLanguage.
        assert!(supports_language("Rust"));
        assert!(supports_language("RUST"));
        assert!(supports_language("C++"));
        assert!(supports_language("TypeScript"));
        // hljs 10.7.3 aliases.
        assert!(supports_language("py"));
        assert!(supports_language("golang"));
        assert!(supports_language("md"));
        assert!(supports_language("ts"));
        assert!(supports_language("tsx"));
        assert!(supports_language("sh"));
        assert!(supports_language("rs"));
        assert!(supports_language("c++"));
        assert!(supports_language("yml"));
        assert!(supports_language("html"));
        assert!(!supports_language("notalang"));
        assert!(!supports_language(""));
    }

    #[test]
    fn every_alias_resolves_in_the_syntax_set() {
        // Self-verifying tables: each entry's syntect target must exist and
        // be fancy-compatible, otherwise the name/alias silently falls back.
        for (alias, target) in CANONICAL_NAME_REDIRECTS.iter().chain(LANGUAGE_ALIASES) {
            assert!(
                supports_language(alias),
                "alias {alias} -> {target} must resolve"
            );
        }
        // No hljs-alias key shadows a canonical name: hljs `getLanguage`
        // resolves names and aliases in one case-insensitive map, so a key
        // that equals another language's name would change that language's
        // resolution. (CANONICAL_NAME_REDIRECTS keys are canonical names by
        // construction and exempt. `html` is exempt too: hljs registers no
        // `html` language — the name only exists as xml's alias — so rpi's
        // extension-table canonical `html` resolves through the same alias
        // semantics as upstream.)
        for (alias, _) in LANGUAGE_ALIASES {
            if *alias == "html" {
                continue;
            }
            assert!(
                !EXT_TO_LANG
                    .iter()
                    .any(|(_, lang)| lang.eq_ignore_ascii_case(alias)),
                "alias {alias} must not collide with a canonical language name"
            );
        }
    }

    // --- highlightCode fallbacks ---------------------------------------------

    #[test]
    fn invalid_language_falls_back_to_md_code_block() {
        let t = theme();
        let code = "fn main() {\n    let x = 1;\n}";
        for lang in [None, Some("notalang"), Some("powershell")] {
            let lines = highlight_code(code, lang, &t);
            assert_eq!(
                lines,
                code.split('\n')
                    .map(|l| t.fg("mdCodeBlock", l))
                    .collect::<Vec<_>>()
            );
        }
    }

    #[test]
    fn invalid_language_fallback_preserves_empty_lines() {
        let t = theme();
        let code = "a\n\nb\n";
        let lines = highlight_code(code, Some("nope"), &t);
        assert_eq!(lines.len(), 4);
        assert_eq!(lines[1], t.fg("mdCodeBlock", ""));
    }

    // --- scope mapping color families ----------------------------------------

    #[test]
    fn rust_tokens_use_distinct_color_families() {
        let t = theme();
        let code = "fn main() {\n    if x == 1 {\n        let s = \"hi\"; // note\n    }\n}\n";
        let lines = highlight_code(code, Some("rust"), &t);
        let out = lines.join("\n");
        let keyword = t.get_fg_ansi("syntaxKeyword");
        let string = t.get_fg_ansi("syntaxString");
        let comment = t.get_fg_ansi("syntaxComment");
        let number = t.get_fg_ansi("syntaxNumber");
        // The three families must be colored differently from each other.
        assert_ne!(keyword, string);
        assert_ne!(keyword, comment);
        assert_ne!(string, comment);
        assert!(out.contains(keyword), "keywords must use syntaxKeyword");
        assert!(out.contains(string), "strings must use syntaxString");
        assert!(out.contains(comment), "comments must use syntaxComment");
        assert!(out.contains(number), "numbers must use syntaxNumber");
        // `fn`/`let` are storage.type in the Rust grammar → syntaxType;
        // `main` is entity.name.function → syntaxFunction.
        assert!(out.contains(t.get_fg_ansi("syntaxType")));
        assert!(out.contains(t.get_fg_ansi("syntaxFunction")));
    }

    // --- highlightCode round-trip --------------------------------------------

    #[test]
    fn highlight_code_emits_ansi_and_strips_back_to_original() {
        let t = theme();
        let code = "fn main() {\n    let x = 1; // comment\n    println!(\"hi\");\n}\n";
        let lines = highlight_code(code, Some("rust"), &t);
        assert_eq!(lines.len(), 5, "trailing newline keeps the empty line");
        for (i, line) in lines.iter().enumerate() {
            let expected = code.split('\n').nth(i).unwrap_or("");
            if expected.is_empty() {
                // Trailing empty element of the upstream split — no text, no
                // color codes.
                assert_eq!(line, "");
                continue;
            }
            assert!(
                line.contains('\x1b'),
                "line {i} must carry ANSI color codes"
            );
            let stripped = strip_ansi(line);
            assert_eq!(stripped, expected, "line {i} must round-trip");
        }
    }

    #[test]
    fn alias_languages_highlight() {
        let t = theme();
        let cases: [(&str, &str, &[&str]); 3] = [
            (
                "csharp",
                "class Foo {\n    string s = \"x\";\n}\n",
                &["syntaxType", "syntaxString", "syntaxVariable"],
            ),
            (
                "protobuf",
                "message Foo {\n    string bar = 1;\n}\n",
                &["syntaxType", "syntaxVariable"],
            ),
            (
                "hcl",
                "resource \"a\" \"b\" {\n    c = 1\n}\n",
                &["syntaxString", "syntaxVariable"],
            ),
        ];
        for (lang, code, needles) in cases {
            let lines = highlight_code(code, Some(lang), &t);
            let out = lines.join("\n");
            assert!(out.contains('\x1b'), "{lang} must produce ANSI colors");
            for needle in needles {
                assert!(
                    out.contains(t.get_fg_ansi(needle)),
                    "{lang} must produce {needle} colors"
                );
            }
            // Round-trip: stripped output equals the input, split by line.
            let stripped: Vec<String> = lines.iter().map(|l| strip_ansi(l)).collect();
            let expected: Vec<String> = code.split('\n').map(str::to_string).collect();
            assert_eq!(stripped, expected, "{lang} must round-trip");
        }
    }
}
